apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: kubernaut-integration
  labels:
    app: postgresql
    component: database
type: Opaque
data:
  # Default password: slm_password_dev (base64 encoded)
  POSTGRES_PASSWORD: c2xtX3Bhc3N3b3JkX2Rldg==
  # Database URL for applications
  DATABASE_URL: cG9zdGdyZXNxbDovL3NsbV91c2VyOnNsbV9wYXNzd29yZF9kZXZAcG9zdGdyZXNxbC1zZXJ2aWNlOjU0MzIvYWN0aW9uX2hpc3Rvcnk=
