# HolmesGPT REST API Container Deployment
# Custom container image with HolmesGPT REST API endpoints
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubernaut-system
  labels:
    name: kubernaut-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holmesgpt-api
  namespace: kubernaut-system
  labels:
    app: holmesgpt-api
    component: ai-investigation
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holmesgpt-api
  template:
    metadata:
      labels:
        app: holmesgpt-api
        component: ai-investigation
        version: v1.0.0
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: holmesgpt-api
        image: kubernaut/holmesgpt-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
        - name: metrics
          containerPort: 9091
          protocol: TCP
        env:
        - name: HOLMESGPT_HOST
          value: "0.0.0.0"
        - name: HOLMESGPT_PORT
          value: "8090"
        - name: HOLMESGPT_METRICS_PORT
          value: "9091"
        - name: HOLMESGPT_LOG_LEVEL
          value: "INFO"
        - name: HOLMESGPT_MODE
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: tmp
        emptyDir: {}
      - name: config
        configMap:
          name: holmesgpt-config
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: holmesgpt-api
  namespace: kubernaut-system
  labels:
    app: holmesgpt-api
    component: ai-investigation
spec:
  selector:
    app: holmesgpt-api
  ports:
  - name: http
    port: 8090
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: metrics
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: holmesgpt-config
  namespace: kubernaut-system
  labels:
    app: holmesgpt-api
    component: ai-investigation
data:
  config.yaml: |
    # HolmesGPT REST API Configuration
    server:
      host: "0.0.0.0"
      port: 8090

    metrics:
      enabled: true
      port: 9091

    logging:
      level: "INFO"
      format: "json"

    llm:
      provider: "local"
      endpoint: "http://localhost:8080"
      timeout: 60

    toolsets:
      - kubernetes
      - prometheus
      - internet

    features:
      async_processing: true
      caching: true
      rate_limiting: true
---
# Optional: Expose service via Route (OpenShift) or Ingress (Kubernetes)
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: holmesgpt-api
  namespace: kubernaut-system
  labels:
    app: holmesgpt-api
    component: ai-investigation
spec:
  to:
    kind: Service
    name: holmesgpt-api
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
