openapi: 3.0.3
info:
  title: Data Storage Service API
  version: 1.0.0
  description: |
    REST API for querying Kubernetes remediation action history.

    This API provides read-only access to incident data stored in PostgreSQL,
    including resource action traces, alert information, and remediation history.

    **Phase 1 (Current)**: Read API only
    **Phase 2 (Future)**: Write API for creating incidents
  contact:
    name: Kubernaut Team
    url: https://github.com/jordigilh/kubernaut
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://data-storage.kubernaut-system.svc.cluster.local:8080
    description: Kubernetes cluster (in-cluster service)
  - url: http://localhost:8080
    description: Local development

tags:
  - name: Incidents
    description: Query remediation action incidents
  - name: Health
    description: Health check endpoints

paths:
  /api/v1/incidents:
    get:
      summary: List incidents with filters
      description: |
        Retrieve a paginated list of incidents filtered by alert name, severity, action type, etc.

        Supports:
        - Filter by alert_name, severity, action_type
        - Pagination with limit/offset
        - Sorting by action_timestamp (DESC)
      operationId: listIncidents
      tags:
        - Incidents
      parameters:
        - name: alert_name
          in: query
          required: false
          schema:
            type: string
          description: Filter by alert name pattern (exact match)
          example: "test-integration-prod-cpu-high"

        - name: severity
          in: query
          required: false
          schema:
            type: string
            enum: [low, medium, high, critical]
          description: Filter by alert severity
          example: "critical"

        - name: action_type
          in: query
          required: false
          schema:
            type: string
          description: Filter by action type (e.g., scale, restart, check)
          example: "scale"

        - name: namespace
          in: query
          required: false
          schema:
            type: string
          description: Filter by Kubernetes namespace
          example: "production"

        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 1000
            default: 100
          description: Maximum number of results to return
          example: 50

        - name: offset
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of results to skip (for pagination)
          example: 100

      responses:
        '200':
          description: Successful response with incident list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentListResponse'
              examples:
                success:
                  summary: Example successful response
                  value:
                    data:
                      - id: 12345
                        alert_name: "prod-cpu-high"
                        alert_severity: "critical"
                        action_type: "scale"
                        action_timestamp: "2025-11-02T10:30:00Z"
                        model_used: "gpt-4"
                        model_confidence: 0.95
                        execution_status: "completed"
                    pagination:
                      total: 1523
                      limit: 100
                      offset: 0
                      has_more: true

        '400':
          description: Bad request - Invalid filter parameters
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RFC7807Error'
              examples:
                invalid_severity:
                  summary: Invalid severity value
                  value:
                    type: "https://kubernaut.io/errors/invalid-filter"
                    title: "Invalid Filter Parameter"
                    status: 400
                    detail: "The 'severity' filter value must be one of: low, medium, high, critical"
                    instance: "/api/v1/incidents"

        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RFC7807Error'
              examples:
                database_error:
                  summary: Database connection error
                  value:
                    type: "https://kubernaut.io/errors/database-error"
                    title: "Database Error"
                    status: 500
                    detail: "Failed to query database: connection timeout"
                    instance: "/api/v1/incidents"

  /api/v1/incidents/{id}:
    get:
      summary: Get incident by ID
      description: Retrieve a single incident by its unique identifier
      operationId: getIncidentByID
      tags:
        - Incidents
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Unique incident ID
          example: 12345

      responses:
        '200':
          description: Successful response with incident details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'
              examples:
                success:
                  summary: Example incident
                  value:
                    id: 12345
                    alert_name: "prod-cpu-high"
                    alert_severity: "critical"
                    action_type: "scale"
                    action_timestamp: "2025-11-02T10:30:00Z"
                    model_used: "gpt-4"
                    model_confidence: 0.95
                    execution_status: "completed"

        '404':
          description: Incident not found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RFC7807Error'
              examples:
                not_found:
                  summary: Incident does not exist
                  value:
                    type: "about:blank"
                    title: "Incident Not Found"
                    status: 404
                    detail: "No incident found with ID: 99999"
                    instance: "/api/v1/incidents/99999"

        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/RFC7807Error'

  /health:
    get:
      summary: Health check endpoint
      description: Check if the service is healthy (application + database)
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
        '503':
          description: Service is unhealthy
          content:
            text/plain:
              schema:
                type: string
                example: "Database connection failed"

  /health/ready:
    get:
      summary: Readiness probe
      description: Check if the service is ready to accept traffic (Kubernetes readiness probe)
      operationId: readinessCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is ready
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
        '503':
          description: Service is not ready (shutting down or starting up)
          content:
            text/plain:
              schema:
                type: string
                example: "Service is shutting down"

  /health/live:
    get:
      summary: Liveness probe
      description: Check if the service is alive (Kubernetes liveness probe)
      operationId: livenessCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is alive
          content:
            text/plain:
              schema:
                type: string
                example: "OK"

components:
  schemas:
    IncidentListResponse:
      type: object
      required:
        - data
        - pagination
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Incident'
          description: Array of incidents matching the filter criteria
        pagination:
          $ref: '#/components/schemas/Pagination'
          description: Pagination metadata

    Incident:
      type: object
      required:
        - id
        - alert_name
        - alert_severity
        - action_type
        - action_timestamp
        - model_used
        - model_confidence
        - execution_status
      properties:
        id:
          type: integer
          format: int64
          description: Unique incident identifier (from resource_action_traces table)
          example: 12345

        alert_name:
          type: string
          description: Name of the Prometheus alert or Kubernetes event
          example: "prod-cpu-high"

        alert_fingerprint:
          type: string
          description: Unique alert fingerprint from Prometheus
          example: "abc123def456"

        alert_severity:
          type: string
          enum: [low, medium, high, critical]
          description: Severity level of the alert
          example: "critical"

        action_type:
          type: string
          description: Type of remediation action taken (e.g., scale, restart, check)
          example: "scale"

        action_timestamp:
          type: string
          format: date-time
          description: Timestamp when the action was executed (ISO 8601)
          example: "2025-11-02T10:30:00Z"

        namespace:
          type: string
          description: Kubernetes namespace where the action was taken
          example: "production"

        cluster_name:
          type: string
          description: Kubernetes cluster identifier
          example: "prod-us-west-2"

        environment:
          type: string
          description: Environment (e.g., production, staging, development)
          example: "production"

        target_resource:
          type: string
          description: Target Kubernetes resource (e.g., deployment/my-app)
          example: "deployment/nginx"

        remediation_request_id:
          type: string
          description: Unique remediation request identifier
          example: "req-abc-123"

        model_used:
          type: string
          description: AI model used for analysis (e.g., gpt-4, claude-3)
          example: "gpt-4"

        model_confidence:
          type: number
          format: double
          minimum: 0.0
          maximum: 1.0
          description: Confidence score from the AI model (0.0 to 1.0)
          example: 0.95

        execution_status:
          type: string
          enum: [pending, in_progress, completed, failed, cancelled]
          description: Current status of the remediation action
          example: "completed"

        start_time:
          type: string
          format: date-time
          description: When the remediation started (ISO 8601)
          example: "2025-11-02T10:30:00Z"

        end_time:
          type: string
          format: date-time
          description: When the remediation completed (ISO 8601)
          example: "2025-11-02T10:35:00Z"

        duration:
          type: integer
          format: int64
          description: Duration of the remediation in milliseconds
          example: 300000

        error_message:
          type: string
          description: Error message if the remediation failed
          example: "Failed to scale deployment: insufficient resources"

        metadata:
          type: string
          description: Additional metadata as JSON string
          example: "{\"replicas_before\":2,\"replicas_after\":5}"

    Pagination:
      type: object
      required:
        - total
        - limit
        - offset
        - has_more
      properties:
        total:
          type: integer
          format: int64
          description: Total number of incidents matching the filter criteria
          example: 1523

        limit:
          type: integer
          description: Maximum number of results returned in this response
          example: 100

        offset:
          type: integer
          description: Number of results skipped (pagination offset)
          example: 0

        has_more:
          type: boolean
          description: Whether there are more results available (for next page)
          example: true

    RFC7807Error:
      type: object
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: URI reference identifying the problem type
          example: "https://kubernaut.io/errors/invalid-filter"

        title:
          type: string
          description: Short, human-readable summary of the problem
          example: "Invalid Filter Parameter"

        status:
          type: integer
          description: HTTP status code
          example: 400

        detail:
          type: string
          description: Human-readable explanation specific to this occurrence
          example: "The 'severity' filter value must be one of: low, medium, high, critical"

        instance:
          type: string
          format: uri
          description: URI reference identifying the specific occurrence of the problem
          example: "/api/v1/incidents"

  securitySchemes:
    # Future: Add authentication when needed
    # BearerAuth:
    #   type: http
    #   scheme: bearer
    #   bearerFormat: JWT

# Future: Add security when authentication is implemented
# security:
#   - BearerAuth: []

