apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubernaut-ingress
  namespace: kubernaut-integration
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      # Webhook service
      - path: /webhook(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: webhook-service
            port:
              number: 8080
      # Prometheus
      - path: /prometheus(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: prometheus-service
            port:
              number: 9090
      # AlertManager
      - path: /alertmanager(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: alertmanager-service
            port:
              number: 9093
      # Metrics endpoints
      - path: /metrics/webhook
        pathType: Prefix
        backend:
          service:
            name: webhook-service
            port:
              number: 9993
---
# Ingress NGINX Controller for Kind
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  # Enable real IP forwarding
  use-forwarded-headers: "true"
  compute-full-forwarded-for: "true"
  # Increase proxy timeouts for AI services
  proxy-connect-timeout: "300"
  proxy-send-timeout: "300"
  proxy-read-timeout: "300"
