apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-alerts-slm
  namespace: prometheus-alerts-slm
  labels:
    app.kubernetes.io/name: prometheus-alerts-slm
    app.kubernetes.io/component: rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-alerts-slm
  labels:
    app.kubernetes.io/name: prometheus-alerts-slm
    app.kubernetes.io/component: rbac
rules:
  # Deployments management
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  
  # ReplicaSets (for deployment scaling)
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list"]
  
  # Pods management
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  
  # Services (for discovery)
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  
  # Namespaces (for cross-namespace operations)
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  
  # Events (for audit trail)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-alerts-slm
  labels:
    app.kubernetes.io/name: prometheus-alerts-slm
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-alerts-slm
subjects:
  - kind: ServiceAccount
    name: prometheus-alerts-slm
    namespace: prometheus-alerts-slm