apiVersion: v1
kind: Service
metadata:
  name: dynamic-toolset
  namespace: kubernaut-system
  labels:
    app: dynamic-toolset
    component: toolset-discovery
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: dynamic-toolset
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-toolset-metrics
  namespace: kubernaut-system
  labels:
    app: dynamic-toolset
    component: toolset-discovery
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: dynamic-toolset
  sessionAffinity: None

