# Local Storage Operator Configuration
# This file contains the configuration for LSO installation and setup

---
# Local Storage Operator Subscription
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: stable
  installPlanApproval: Automatic
  name: local-storage-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

---
# Local Storage Operator Group
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: local-storage
  namespace: openshift-local-storage
spec:
  targetNamespaces:
  - openshift-local-storage

---
# Local Volume Discovery
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
  name: auto-discover-devices
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: node-role.kubernetes.io/worker
        operator: Exists

---
# Local Volume Set for Block Storage
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: local-block-storage
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
  storageClassName: local-block
  volumeMode: Block
  fsType: ""
  maxDeviceCount: 10
  deviceInclusionSpec:
    deviceTypes:
    - disk
    - part
    deviceMechanicalProperties:
    - NonRotational
    - Rotational
    minSize: 10Gi
  tolerations:
  - key: local-storage
    operator: Equal
    value: "true"
    effect: NoSchedule

---
# Local Volume for File System Storage
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-filesystem-storage
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/worker
        operator: Exists
  storageClassDevices:
  - storageClassName: local-filesystem
    volumeMode: Filesystem
    fsType: xfs
    devicePaths:
    - /dev/sdb
    - /dev/sdc
