#!/bin/bash
# Script to generate Python Pydantic models from DataStorage OpenAPI spec
# for audit event payloads
#
# This eliminates duplicate type definitions between Python (Pydantic) and OpenAPI
#
# Usage: ./generate-audit-types.sh
#
# Requirements: datamodel-codegen (pip install datamodel-code-generator)

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_ROOT="$(dirname "$PROJECT_DIR")"

OPENAPI_SPEC="${WORKSPACE_ROOT}/api/openapi/data-storage-v1.yaml"
OUTPUT_FILE="${PROJECT_DIR}/src/models/generated_audit_types.py"

echo "🔧 Generating Python audit types from DataStorage OpenAPI spec..."
echo "   Spec: ${OPENAPI_SPEC}"
echo "   Output: ${OUTPUT_FILE}"

# Check if spec exists
if [ ! -f "${OPENAPI_SPEC}" ]; then
    echo "❌ OpenAPI spec not found at ${OPENAPI_SPEC}"
    exit 1
fi

# Check if datamodel-codegen is installed
if ! command -v datamodel-codegen &> /dev/null; then
    echo "❌ datamodel-codegen not found. Install with:"
    echo "   pip install datamodel-code-generator"
    exit 1
fi

# Generate Python models
echo "🐍 Running datamodel-codegen..."
datamodel-codegen \
  --input "${OPENAPI_SPEC}" \
  --input-file-type openapi \
  --output "${OUTPUT_FILE}" \
  --output-model-type pydantic_v2.BaseModel \
  --field-constraints \
  --use-standard-collections \
  --use-schema-description \
  --use-field-description \
  --snake-case-field \
  --strict-nullable \
  --target-python-version 3.11

echo "✅ Python audit types generated to ${OUTPUT_FILE}"

# Add header comment
TEMP_FILE="${OUTPUT_FILE}.tmp"
cat > "${TEMP_FILE}" << 'EOF'
"""
Auto-generated audit event payload types from DataStorage OpenAPI spec.

DO NOT EDIT THIS FILE MANUALLY - it is auto-generated from:
  api/openapi/data-storage-v1.yaml

To regenerate:
  cd holmesgpt-api && ./scripts/generate-audit-types.sh

Authority: OpenAPI spec is single source of truth for audit payloads
Related: DD-AUDIT-004 (Structured Types for Audit Event Payloads)
"""

EOF

cat "${OUTPUT_FILE}" >> "${TEMP_FILE}"
mv "${TEMP_FILE}" "${OUTPUT_FILE}"

echo "✅ Header comment added"

# Format with black
if command -v black &> /dev/null; then
    echo "🎨 Formatting with black..."
    black "${OUTPUT_FILE}"
fi

echo ""
echo "✨ Generation complete!"
echo ""
echo "📝 Next steps:"
echo "   1. Review generated types in ${OUTPUT_FILE}"
echo "   2. Replace manual Pydantic models in src/models/audit_models.py"
echo "   3. Update imports in src/audit/events.py"
echo "   4. Run tests: pytest tests/"
echo ""

