{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.aianalysis.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubernaut.fullname" . }}-aianalysis
  namespace: {{ .Release.Namespace }}
  labels:
    app: aianalysis-controller
    {{- include "kubernaut.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: aianalysis-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- include "kubernaut.np.metricsIngress" $ | nindent 4 }}
  egress:
    {{- include "kubernaut.np.commonEgress" . | nindent 4 }}
    {{- include "kubernaut.np.datastorageEgress" . | nindent 4 }}
    - ports:
        - port: 8443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app: kubernaut-agent
{{- end }}
