// Code generated by ogen, DO NOT EDIT.

package holmesgpt

import (
	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

// Auto-detected cluster characteristics from SignalProcessing.
// These labels are used for:
// 1. LLM context (natural language) - help LLM understand cluster environment
// 2. MCP workflow filtering - filter workflows to only compatible ones
// Design Decision: DD-RECOVERY-003.
// Ref: #/components/schemas/DetectedLabels
type DetectedLabels struct {
	// Whether namespace is managed by GitOps.
	GitOpsManaged OptBool `json:"gitOpsManaged"`
	// GitOps tool: 'argocd', 'flux', or ''.
	GitOpsTool OptString `json:"gitOpsTool"`
	// Whether PodDisruptionBudget protects this workload.
	PdbProtected OptBool `json:"pdbProtected"`
	// Whether HorizontalPodAutoscaler is active.
	HpaEnabled OptBool `json:"hpaEnabled"`
	// Whether this is a stateful workload (StatefulSet or has PVCs).
	Stateful OptBool `json:"stateful"`
	// Whether resource is managed by Helm.
	HelmManaged OptBool `json:"helmManaged"`
	// Whether NetworkPolicy restricts traffic.
	NetworkIsolated OptBool `json:"networkIsolated"`
	// Pod Security Standard: 'privileged', 'baseline', 'restricted', ''.
	PodSecurityLevel OptString `json:"podSecurityLevel"`
	// Service mesh: 'istio', 'linkerd', ''.
	ServiceMesh OptString `json:"serviceMesh"`
}

// GetGitOpsManaged returns the value of GitOpsManaged.
func (s *DetectedLabels) GetGitOpsManaged() OptBool {
	return s.GitOpsManaged
}

// GetGitOpsTool returns the value of GitOpsTool.
func (s *DetectedLabels) GetGitOpsTool() OptString {
	return s.GitOpsTool
}

// GetPdbProtected returns the value of PdbProtected.
func (s *DetectedLabels) GetPdbProtected() OptBool {
	return s.PdbProtected
}

// GetHpaEnabled returns the value of HpaEnabled.
func (s *DetectedLabels) GetHpaEnabled() OptBool {
	return s.HpaEnabled
}

// GetStateful returns the value of Stateful.
func (s *DetectedLabels) GetStateful() OptBool {
	return s.Stateful
}

// GetHelmManaged returns the value of HelmManaged.
func (s *DetectedLabels) GetHelmManaged() OptBool {
	return s.HelmManaged
}

// GetNetworkIsolated returns the value of NetworkIsolated.
func (s *DetectedLabels) GetNetworkIsolated() OptBool {
	return s.NetworkIsolated
}

// GetPodSecurityLevel returns the value of PodSecurityLevel.
func (s *DetectedLabels) GetPodSecurityLevel() OptString {
	return s.PodSecurityLevel
}

// GetServiceMesh returns the value of ServiceMesh.
func (s *DetectedLabels) GetServiceMesh() OptString {
	return s.ServiceMesh
}

// SetGitOpsManaged sets the value of GitOpsManaged.
func (s *DetectedLabels) SetGitOpsManaged(val OptBool) {
	s.GitOpsManaged = val
}

// SetGitOpsTool sets the value of GitOpsTool.
func (s *DetectedLabels) SetGitOpsTool(val OptString) {
	s.GitOpsTool = val
}

// SetPdbProtected sets the value of PdbProtected.
func (s *DetectedLabels) SetPdbProtected(val OptBool) {
	s.PdbProtected = val
}

// SetHpaEnabled sets the value of HpaEnabled.
func (s *DetectedLabels) SetHpaEnabled(val OptBool) {
	s.HpaEnabled = val
}

// SetStateful sets the value of Stateful.
func (s *DetectedLabels) SetStateful(val OptBool) {
	s.Stateful = val
}

// SetHelmManaged sets the value of HelmManaged.
func (s *DetectedLabels) SetHelmManaged(val OptBool) {
	s.HelmManaged = val
}

// SetNetworkIsolated sets the value of NetworkIsolated.
func (s *DetectedLabels) SetNetworkIsolated(val OptBool) {
	s.NetworkIsolated = val
}

// SetPodSecurityLevel sets the value of PodSecurityLevel.
func (s *DetectedLabels) SetPodSecurityLevel(val OptString) {
	s.PodSecurityLevel = val
}

// SetServiceMesh sets the value of ServiceMesh.
func (s *DetectedLabels) SetServiceMesh(val OptString) {
	s.ServiceMesh = val
}

// Assessment of execution effectiveness.
// Ref: #/components/schemas/EffectivenessAssessment
type EffectivenessAssessment struct {
	// Whether execution achieved objectives.
	Success bool `json:"success"`
	// Confidence in assessment.
	Confidence float64 `json:"confidence"`
	// Detailed reasoning for assessment.
	Reasoning string `json:"reasoning"`
	// Analysis of metrics.
	MetricsAnalysis OptEffectivenessAssessmentMetricsAnalysis `json:"metrics_analysis"`
}

// GetSuccess returns the value of Success.
func (s *EffectivenessAssessment) GetSuccess() bool {
	return s.Success
}

// GetConfidence returns the value of Confidence.
func (s *EffectivenessAssessment) GetConfidence() float64 {
	return s.Confidence
}

// GetReasoning returns the value of Reasoning.
func (s *EffectivenessAssessment) GetReasoning() string {
	return s.Reasoning
}

// GetMetricsAnalysis returns the value of MetricsAnalysis.
func (s *EffectivenessAssessment) GetMetricsAnalysis() OptEffectivenessAssessmentMetricsAnalysis {
	return s.MetricsAnalysis
}

// SetSuccess sets the value of Success.
func (s *EffectivenessAssessment) SetSuccess(val bool) {
	s.Success = val
}

// SetConfidence sets the value of Confidence.
func (s *EffectivenessAssessment) SetConfidence(val float64) {
	s.Confidence = val
}

// SetReasoning sets the value of Reasoning.
func (s *EffectivenessAssessment) SetReasoning(val string) {
	s.Reasoning = val
}

// SetMetricsAnalysis sets the value of MetricsAnalysis.
func (s *EffectivenessAssessment) SetMetricsAnalysis(val OptEffectivenessAssessmentMetricsAnalysis) {
	s.MetricsAnalysis = val
}

// Analysis of metrics.
type EffectivenessAssessmentMetricsAnalysis map[string]jx.Raw

func (s *EffectivenessAssessmentMetricsAnalysis) init() EffectivenessAssessmentMetricsAnalysis {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Enrichment results from SignalProcessing.
// Contains Kubernetes context, auto-detected labels, and custom labels
// that are used for workflow filtering and LLM context.
// Design Decision: DD-RECOVERY-003, DD-HAPI-001
// Custom Labels (DD-HAPI-001):
// - Format: map[string][]string (subdomain → list of values)
// - Keys are subdomains (e.g., "constraint", "team")
// - Values are lists of strings (boolean keys or "key=value" pairs)
// - Example: {"constraint": ["cost-constrained"], "team": ["name=payments"]}
// - Auto-appended to MCP workflow search (invisible to LLM).
// Ref: #/components/schemas/EnrichmentResults
type EnrichmentResults struct {
	// Kubernetes resource context.
	KubernetesContext OptNilEnrichmentResultsKubernetesContext `json:"kubernetesContext"`
	// Auto-detected cluster characteristics.
	DetectedLabels OptNilDetectedLabels `json:"detectedLabels"`
	// Custom labels from SignalProcessing (subdomain → values). Auto-appended to workflow search per
	// DD-HAPI-001.
	CustomLabels OptNilEnrichmentResultsCustomLabels `json:"customLabels"`
	// Quality score of enrichment (0-1).
	EnrichmentQuality OptFloat64 `json:"enrichmentQuality"`
}

// GetKubernetesContext returns the value of KubernetesContext.
func (s *EnrichmentResults) GetKubernetesContext() OptNilEnrichmentResultsKubernetesContext {
	return s.KubernetesContext
}

// GetDetectedLabels returns the value of DetectedLabels.
func (s *EnrichmentResults) GetDetectedLabels() OptNilDetectedLabels {
	return s.DetectedLabels
}

// GetCustomLabels returns the value of CustomLabels.
func (s *EnrichmentResults) GetCustomLabels() OptNilEnrichmentResultsCustomLabels {
	return s.CustomLabels
}

// GetEnrichmentQuality returns the value of EnrichmentQuality.
func (s *EnrichmentResults) GetEnrichmentQuality() OptFloat64 {
	return s.EnrichmentQuality
}

// SetKubernetesContext sets the value of KubernetesContext.
func (s *EnrichmentResults) SetKubernetesContext(val OptNilEnrichmentResultsKubernetesContext) {
	s.KubernetesContext = val
}

// SetDetectedLabels sets the value of DetectedLabels.
func (s *EnrichmentResults) SetDetectedLabels(val OptNilDetectedLabels) {
	s.DetectedLabels = val
}

// SetCustomLabels sets the value of CustomLabels.
func (s *EnrichmentResults) SetCustomLabels(val OptNilEnrichmentResultsCustomLabels) {
	s.CustomLabels = val
}

// SetEnrichmentQuality sets the value of EnrichmentQuality.
func (s *EnrichmentResults) SetEnrichmentQuality(val OptFloat64) {
	s.EnrichmentQuality = val
}

type EnrichmentResultsCustomLabels map[string][]string

func (s *EnrichmentResultsCustomLabels) init() EnrichmentResultsCustomLabels {
	m := *s
	if m == nil {
		m = map[string][]string{}
		*s = m
	}
	return m
}

type EnrichmentResultsKubernetesContext map[string]jx.Raw

func (s *EnrichmentResultsKubernetesContext) init() EnrichmentResultsKubernetesContext {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Structured failure information using Kubernetes reason codes.
// CRITICAL: The 'reason' field uses canonical Kubernetes reason codes as the API contract.
// This is NOT natural language - it's a structured enum-like value.
// Valid reason codes include:
// - Resource: OOMKilled, InsufficientCPU, InsufficientMemory, Evicted
// - Scheduling: FailedScheduling, Unschedulable
// - Image: ImagePullBackOff, ErrImagePull, InvalidImageName
// - Execution: DeadlineExceeded, BackoffLimitExceeded, Error
// - Permission: Unauthorized, Forbidden
// - Volume: FailedMount, FailedAttachVolume
// - Node: NodeNotReady, NodeUnreachable
// - Network: NetworkNotReady.
// Ref: #/components/schemas/ExecutionFailure
type ExecutionFailure struct {
	// 0-indexed step that failed.
	FailedStepIndex int `json:"failed_step_index"`
	// Name of the failed step.
	FailedStepName string `json:"failed_step_name"`
	// Kubernetes reason code (e.g., 'OOMKilled', 'DeadlineExceeded'). NOT natural language.
	Reason string `json:"reason"`
	// Human-readable error message (for logging/debugging).
	Message string `json:"message"`
	// Exit code if applicable.
	ExitCode OptNilInt `json:"exit_code"`
	// ISO timestamp of failure.
	FailedAt string `json:"failed_at"`
	// Duration before failure (e.g., '2m34s').
	ExecutionTime string `json:"execution_time"`
}

// GetFailedStepIndex returns the value of FailedStepIndex.
func (s *ExecutionFailure) GetFailedStepIndex() int {
	return s.FailedStepIndex
}

// GetFailedStepName returns the value of FailedStepName.
func (s *ExecutionFailure) GetFailedStepName() string {
	return s.FailedStepName
}

// GetReason returns the value of Reason.
func (s *ExecutionFailure) GetReason() string {
	return s.Reason
}

// GetMessage returns the value of Message.
func (s *ExecutionFailure) GetMessage() string {
	return s.Message
}

// GetExitCode returns the value of ExitCode.
func (s *ExecutionFailure) GetExitCode() OptNilInt {
	return s.ExitCode
}

// GetFailedAt returns the value of FailedAt.
func (s *ExecutionFailure) GetFailedAt() string {
	return s.FailedAt
}

// GetExecutionTime returns the value of ExecutionTime.
func (s *ExecutionFailure) GetExecutionTime() string {
	return s.ExecutionTime
}

// SetFailedStepIndex sets the value of FailedStepIndex.
func (s *ExecutionFailure) SetFailedStepIndex(val int) {
	s.FailedStepIndex = val
}

// SetFailedStepName sets the value of FailedStepName.
func (s *ExecutionFailure) SetFailedStepName(val string) {
	s.FailedStepName = val
}

// SetReason sets the value of Reason.
func (s *ExecutionFailure) SetReason(val string) {
	s.Reason = val
}

// SetMessage sets the value of Message.
func (s *ExecutionFailure) SetMessage(val string) {
	s.Message = val
}

// SetExitCode sets the value of ExitCode.
func (s *ExecutionFailure) SetExitCode(val OptNilInt) {
	s.ExitCode = val
}

// SetFailedAt sets the value of FailedAt.
func (s *ExecutionFailure) SetFailedAt(val string) {
	s.FailedAt = val
}

// SetExecutionTime sets the value of ExecutionTime.
func (s *ExecutionFailure) SetExecutionTime(val string) {
	s.ExecutionTime = val
}

// Ref: #/components/schemas/HTTPValidationError
type HTTPValidationError struct {
	Detail []ValidationError `json:"detail"`
}

// GetDetail returns the value of Detail.
func (s *HTTPValidationError) GetDetail() []ValidationError {
	return s.Detail
}

// SetDetail sets the value of Detail.
func (s *HTTPValidationError) SetDetail(val []ValidationError) {
	s.Detail = val
}

func (*HTTPValidationError) incidentAnalyzeEndpointAPIV1IncidentAnalyzePostRes() {}
func (*HTTPValidationError) postexecAnalyzeEndpointAPIV1PostexecAnalyzePostRes() {}
func (*HTTPValidationError) recoveryAnalyzeEndpointAPIV1RecoveryAnalyzePostRes() {}

// Request model for initial incident analysis endpoint
// Business Requirements:
// - BR-HAPI-002: Incident analysis request schema
// - BR-AUDIT-001: Unified audit trail (remediation_id)
// Design Decision: DD-WORKFLOW-002 v2.2
// - remediation_id is MANDATORY for audit trail correlation
// - remediation_id is for CORRELATION ONLY - do NOT use for RCA or workflow matching
// Design Decision: DD-RECOVERY-003
// - enrichment_results contains DetectedLabels for workflow filtering.
// Ref: #/components/schemas/IncidentRequest
type IncidentRequest struct {
	// Unique incident identifier.
	IncidentID string `json:"incident_id"`
	// Remediation request ID for audit correlation (e.g., 'req-2025-11-27-abc123'). MANDATORY per
	// DD-WORKFLOW-002 v2.2. This ID is for CORRELATION/AUDIT ONLY - do NOT use for RCA analysis or
	// workflow matching.
	RemediationID string `json:"remediation_id"`
	// Canonical signal type.
	SignalType string `json:"signal_type"`
	// Signal severity.
	Severity string `json:"severity"`
	// Monitoring system.
	SignalSource string `json:"signal_source"`
	// Kubernetes namespace.
	ResourceNamespace string `json:"resource_namespace"`
	// Kubernetes resource kind.
	ResourceKind string `json:"resource_kind"`
	// Resource name.
	ResourceName string `json:"resource_name"`
	// Error message.
	ErrorMessage string `json:"error_message"`
	// Additional description.
	Description OptNilString `json:"description"`
	// Deployment environment.
	Environment string `json:"environment"`
	// Business priority.
	Priority string `json:"priority"`
	// Risk tolerance.
	RiskTolerance string `json:"risk_tolerance"`
	// Business category.
	BusinessCategory string `json:"business_category"`
	// Kubernetes cluster name.
	ClusterName string `json:"cluster_name"`
	// Duplicate signal.
	IsDuplicate OptNilBool `json:"is_duplicate"`
	// Occurrence count.
	OccurrenceCount OptNilInt `json:"occurrence_count"`
	// Dedup window.
	DeduplicationWindowMinutes OptNilInt `json:"deduplication_window_minutes"`
	// Storm detected.
	IsStorm OptNilBool `json:"is_storm"`
	// Storm signal count.
	StormSignalCount OptNilInt `json:"storm_signal_count"`
	// Storm window.
	StormWindowMinutes OptNilInt `json:"storm_window_minutes"`
	// Storm type.
	StormType OptNilString `json:"storm_type"`
	// Affected resources.
	AffectedResources OptNilStringArray `json:"affected_resources"`
	// Firing time.
	FiringTime OptNilString `json:"firing_time"`
	// Received time.
	ReceivedTime OptNilString `json:"received_time"`
	// First seen.
	FirstSeen OptNilString `json:"first_seen"`
	// Last seen.
	LastSeen OptNilString `json:"last_seen"`
	// Signal labels.
	SignalLabels OptNilIncidentRequestSignalLabels `json:"signal_labels"`
	// Enriched context from SignalProcessing.
	EnrichmentResults OptNilEnrichmentResults `json:"enrichment_results"`
}

// GetIncidentID returns the value of IncidentID.
func (s *IncidentRequest) GetIncidentID() string {
	return s.IncidentID
}

// GetRemediationID returns the value of RemediationID.
func (s *IncidentRequest) GetRemediationID() string {
	return s.RemediationID
}

// GetSignalType returns the value of SignalType.
func (s *IncidentRequest) GetSignalType() string {
	return s.SignalType
}

// GetSeverity returns the value of Severity.
func (s *IncidentRequest) GetSeverity() string {
	return s.Severity
}

// GetSignalSource returns the value of SignalSource.
func (s *IncidentRequest) GetSignalSource() string {
	return s.SignalSource
}

// GetResourceNamespace returns the value of ResourceNamespace.
func (s *IncidentRequest) GetResourceNamespace() string {
	return s.ResourceNamespace
}

// GetResourceKind returns the value of ResourceKind.
func (s *IncidentRequest) GetResourceKind() string {
	return s.ResourceKind
}

// GetResourceName returns the value of ResourceName.
func (s *IncidentRequest) GetResourceName() string {
	return s.ResourceName
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *IncidentRequest) GetErrorMessage() string {
	return s.ErrorMessage
}

// GetDescription returns the value of Description.
func (s *IncidentRequest) GetDescription() OptNilString {
	return s.Description
}

// GetEnvironment returns the value of Environment.
func (s *IncidentRequest) GetEnvironment() string {
	return s.Environment
}

// GetPriority returns the value of Priority.
func (s *IncidentRequest) GetPriority() string {
	return s.Priority
}

// GetRiskTolerance returns the value of RiskTolerance.
func (s *IncidentRequest) GetRiskTolerance() string {
	return s.RiskTolerance
}

// GetBusinessCategory returns the value of BusinessCategory.
func (s *IncidentRequest) GetBusinessCategory() string {
	return s.BusinessCategory
}

// GetClusterName returns the value of ClusterName.
func (s *IncidentRequest) GetClusterName() string {
	return s.ClusterName
}

// GetIsDuplicate returns the value of IsDuplicate.
func (s *IncidentRequest) GetIsDuplicate() OptNilBool {
	return s.IsDuplicate
}

// GetOccurrenceCount returns the value of OccurrenceCount.
func (s *IncidentRequest) GetOccurrenceCount() OptNilInt {
	return s.OccurrenceCount
}

// GetDeduplicationWindowMinutes returns the value of DeduplicationWindowMinutes.
func (s *IncidentRequest) GetDeduplicationWindowMinutes() OptNilInt {
	return s.DeduplicationWindowMinutes
}

// GetIsStorm returns the value of IsStorm.
func (s *IncidentRequest) GetIsStorm() OptNilBool {
	return s.IsStorm
}

// GetStormSignalCount returns the value of StormSignalCount.
func (s *IncidentRequest) GetStormSignalCount() OptNilInt {
	return s.StormSignalCount
}

// GetStormWindowMinutes returns the value of StormWindowMinutes.
func (s *IncidentRequest) GetStormWindowMinutes() OptNilInt {
	return s.StormWindowMinutes
}

// GetStormType returns the value of StormType.
func (s *IncidentRequest) GetStormType() OptNilString {
	return s.StormType
}

// GetAffectedResources returns the value of AffectedResources.
func (s *IncidentRequest) GetAffectedResources() OptNilStringArray {
	return s.AffectedResources
}

// GetFiringTime returns the value of FiringTime.
func (s *IncidentRequest) GetFiringTime() OptNilString {
	return s.FiringTime
}

// GetReceivedTime returns the value of ReceivedTime.
func (s *IncidentRequest) GetReceivedTime() OptNilString {
	return s.ReceivedTime
}

// GetFirstSeen returns the value of FirstSeen.
func (s *IncidentRequest) GetFirstSeen() OptNilString {
	return s.FirstSeen
}

// GetLastSeen returns the value of LastSeen.
func (s *IncidentRequest) GetLastSeen() OptNilString {
	return s.LastSeen
}

// GetSignalLabels returns the value of SignalLabels.
func (s *IncidentRequest) GetSignalLabels() OptNilIncidentRequestSignalLabels {
	return s.SignalLabels
}

// GetEnrichmentResults returns the value of EnrichmentResults.
func (s *IncidentRequest) GetEnrichmentResults() OptNilEnrichmentResults {
	return s.EnrichmentResults
}

// SetIncidentID sets the value of IncidentID.
func (s *IncidentRequest) SetIncidentID(val string) {
	s.IncidentID = val
}

// SetRemediationID sets the value of RemediationID.
func (s *IncidentRequest) SetRemediationID(val string) {
	s.RemediationID = val
}

// SetSignalType sets the value of SignalType.
func (s *IncidentRequest) SetSignalType(val string) {
	s.SignalType = val
}

// SetSeverity sets the value of Severity.
func (s *IncidentRequest) SetSeverity(val string) {
	s.Severity = val
}

// SetSignalSource sets the value of SignalSource.
func (s *IncidentRequest) SetSignalSource(val string) {
	s.SignalSource = val
}

// SetResourceNamespace sets the value of ResourceNamespace.
func (s *IncidentRequest) SetResourceNamespace(val string) {
	s.ResourceNamespace = val
}

// SetResourceKind sets the value of ResourceKind.
func (s *IncidentRequest) SetResourceKind(val string) {
	s.ResourceKind = val
}

// SetResourceName sets the value of ResourceName.
func (s *IncidentRequest) SetResourceName(val string) {
	s.ResourceName = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *IncidentRequest) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// SetDescription sets the value of Description.
func (s *IncidentRequest) SetDescription(val OptNilString) {
	s.Description = val
}

// SetEnvironment sets the value of Environment.
func (s *IncidentRequest) SetEnvironment(val string) {
	s.Environment = val
}

// SetPriority sets the value of Priority.
func (s *IncidentRequest) SetPriority(val string) {
	s.Priority = val
}

// SetRiskTolerance sets the value of RiskTolerance.
func (s *IncidentRequest) SetRiskTolerance(val string) {
	s.RiskTolerance = val
}

// SetBusinessCategory sets the value of BusinessCategory.
func (s *IncidentRequest) SetBusinessCategory(val string) {
	s.BusinessCategory = val
}

// SetClusterName sets the value of ClusterName.
func (s *IncidentRequest) SetClusterName(val string) {
	s.ClusterName = val
}

// SetIsDuplicate sets the value of IsDuplicate.
func (s *IncidentRequest) SetIsDuplicate(val OptNilBool) {
	s.IsDuplicate = val
}

// SetOccurrenceCount sets the value of OccurrenceCount.
func (s *IncidentRequest) SetOccurrenceCount(val OptNilInt) {
	s.OccurrenceCount = val
}

// SetDeduplicationWindowMinutes sets the value of DeduplicationWindowMinutes.
func (s *IncidentRequest) SetDeduplicationWindowMinutes(val OptNilInt) {
	s.DeduplicationWindowMinutes = val
}

// SetIsStorm sets the value of IsStorm.
func (s *IncidentRequest) SetIsStorm(val OptNilBool) {
	s.IsStorm = val
}

// SetStormSignalCount sets the value of StormSignalCount.
func (s *IncidentRequest) SetStormSignalCount(val OptNilInt) {
	s.StormSignalCount = val
}

// SetStormWindowMinutes sets the value of StormWindowMinutes.
func (s *IncidentRequest) SetStormWindowMinutes(val OptNilInt) {
	s.StormWindowMinutes = val
}

// SetStormType sets the value of StormType.
func (s *IncidentRequest) SetStormType(val OptNilString) {
	s.StormType = val
}

// SetAffectedResources sets the value of AffectedResources.
func (s *IncidentRequest) SetAffectedResources(val OptNilStringArray) {
	s.AffectedResources = val
}

// SetFiringTime sets the value of FiringTime.
func (s *IncidentRequest) SetFiringTime(val OptNilString) {
	s.FiringTime = val
}

// SetReceivedTime sets the value of ReceivedTime.
func (s *IncidentRequest) SetReceivedTime(val OptNilString) {
	s.ReceivedTime = val
}

// SetFirstSeen sets the value of FirstSeen.
func (s *IncidentRequest) SetFirstSeen(val OptNilString) {
	s.FirstSeen = val
}

// SetLastSeen sets the value of LastSeen.
func (s *IncidentRequest) SetLastSeen(val OptNilString) {
	s.LastSeen = val
}

// SetSignalLabels sets the value of SignalLabels.
func (s *IncidentRequest) SetSignalLabels(val OptNilIncidentRequestSignalLabels) {
	s.SignalLabels = val
}

// SetEnrichmentResults sets the value of EnrichmentResults.
func (s *IncidentRequest) SetEnrichmentResults(val OptNilEnrichmentResults) {
	s.EnrichmentResults = val
}

type IncidentRequestSignalLabels map[string]string

func (s *IncidentRequestSignalLabels) init() IncidentRequestSignalLabels {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Response model for incident analysis endpoint
// Business Requirement: BR-HAPI-002 (Incident analysis response schema)
// Design Decision: DD-WORKFLOW-001 v1.7 (OwnerChain validation)
// New fields (per AIAnalysis team request, Dec 2, 2025):
// - target_in_owner_chain: Whether RCA target was found in OwnerChain
// - warnings: Non-fatal warnings for transparency.
// Ref: #/components/schemas/IncidentResponse
type IncidentResponse struct {
	// Incident identifier from request.
	IncidentID string `json:"incident_id"`
	// Natural language analysis from LLM.
	Analysis string `json:"analysis"`
	// Structured RCA with summary, severity, contributing_factors.
	RootCauseAnalysis IncidentResponseRootCauseAnalysis `json:"root_cause_analysis"`
	// Selected workflow with workflow_id, containerImage, confidence, parameters.
	SelectedWorkflow OptNilIncidentResponseSelectedWorkflow `json:"selected_workflow"`
	// Overall confidence in analysis.
	Confidence float64 `json:"confidence"`
	// ISO timestamp of analysis completion.
	Timestamp string `json:"timestamp"`
	// Whether RCA-identified target resource was found in OwnerChain. If false, DetectedLabels may be
	// from different scope than affected resource.
	TargetInOwnerChain OptBool `json:"target_in_owner_chain"`
	// Non-fatal warnings (e.g., OwnerChain validation issues, low confidence).
	Warnings []string `json:"warnings"`
}

// GetIncidentID returns the value of IncidentID.
func (s *IncidentResponse) GetIncidentID() string {
	return s.IncidentID
}

// GetAnalysis returns the value of Analysis.
func (s *IncidentResponse) GetAnalysis() string {
	return s.Analysis
}

// GetRootCauseAnalysis returns the value of RootCauseAnalysis.
func (s *IncidentResponse) GetRootCauseAnalysis() IncidentResponseRootCauseAnalysis {
	return s.RootCauseAnalysis
}

// GetSelectedWorkflow returns the value of SelectedWorkflow.
func (s *IncidentResponse) GetSelectedWorkflow() OptNilIncidentResponseSelectedWorkflow {
	return s.SelectedWorkflow
}

// GetConfidence returns the value of Confidence.
func (s *IncidentResponse) GetConfidence() float64 {
	return s.Confidence
}

// GetTimestamp returns the value of Timestamp.
func (s *IncidentResponse) GetTimestamp() string {
	return s.Timestamp
}

// GetTargetInOwnerChain returns the value of TargetInOwnerChain.
func (s *IncidentResponse) GetTargetInOwnerChain() OptBool {
	return s.TargetInOwnerChain
}

// GetWarnings returns the value of Warnings.
func (s *IncidentResponse) GetWarnings() []string {
	return s.Warnings
}

// SetIncidentID sets the value of IncidentID.
func (s *IncidentResponse) SetIncidentID(val string) {
	s.IncidentID = val
}

// SetAnalysis sets the value of Analysis.
func (s *IncidentResponse) SetAnalysis(val string) {
	s.Analysis = val
}

// SetRootCauseAnalysis sets the value of RootCauseAnalysis.
func (s *IncidentResponse) SetRootCauseAnalysis(val IncidentResponseRootCauseAnalysis) {
	s.RootCauseAnalysis = val
}

// SetSelectedWorkflow sets the value of SelectedWorkflow.
func (s *IncidentResponse) SetSelectedWorkflow(val OptNilIncidentResponseSelectedWorkflow) {
	s.SelectedWorkflow = val
}

// SetConfidence sets the value of Confidence.
func (s *IncidentResponse) SetConfidence(val float64) {
	s.Confidence = val
}

// SetTimestamp sets the value of Timestamp.
func (s *IncidentResponse) SetTimestamp(val string) {
	s.Timestamp = val
}

// SetTargetInOwnerChain sets the value of TargetInOwnerChain.
func (s *IncidentResponse) SetTargetInOwnerChain(val OptBool) {
	s.TargetInOwnerChain = val
}

// SetWarnings sets the value of Warnings.
func (s *IncidentResponse) SetWarnings(val []string) {
	s.Warnings = val
}

func (*IncidentResponse) incidentAnalyzeEndpointAPIV1IncidentAnalyzePostRes() {}

// Structured RCA with summary, severity, contributing_factors.
type IncidentResponseRootCauseAnalysis map[string]jx.Raw

func (s *IncidentResponseRootCauseAnalysis) init() IncidentResponseRootCauseAnalysis {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type IncidentResponseSelectedWorkflow map[string]jx.Raw

func (s *IncidentResponseSelectedWorkflow) init() IncidentResponseSelectedWorkflow {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptEffectivenessAssessmentMetricsAnalysis returns new OptEffectivenessAssessmentMetricsAnalysis with value set to v.
func NewOptEffectivenessAssessmentMetricsAnalysis(v EffectivenessAssessmentMetricsAnalysis) OptEffectivenessAssessmentMetricsAnalysis {
	return OptEffectivenessAssessmentMetricsAnalysis{
		Value: v,
		Set:   true,
	}
}

// OptEffectivenessAssessmentMetricsAnalysis is optional EffectivenessAssessmentMetricsAnalysis.
type OptEffectivenessAssessmentMetricsAnalysis struct {
	Value EffectivenessAssessmentMetricsAnalysis
	Set   bool
}

// IsSet returns true if OptEffectivenessAssessmentMetricsAnalysis was set.
func (o OptEffectivenessAssessmentMetricsAnalysis) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptEffectivenessAssessmentMetricsAnalysis) Reset() {
	var v EffectivenessAssessmentMetricsAnalysis
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptEffectivenessAssessmentMetricsAnalysis) SetTo(v EffectivenessAssessmentMetricsAnalysis) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptEffectivenessAssessmentMetricsAnalysis) Get() (v EffectivenessAssessmentMetricsAnalysis, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptEffectivenessAssessmentMetricsAnalysis) Or(d EffectivenessAssessmentMetricsAnalysis) EffectivenessAssessmentMetricsAnalysis {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilBool returns new OptNilBool with value set to v.
func NewOptNilBool(v bool) OptNilBool {
	return OptNilBool{
		Value: v,
		Set:   true,
	}
}

// OptNilBool is optional nullable bool.
type OptNilBool struct {
	Value bool
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilBool was set.
func (o OptNilBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilBool) SetTo(v bool) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilBool) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilBool) SetToNull() {
	o.Set = true
	o.Null = true
	var v bool
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilBool) Get() (v bool, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDetectedLabels returns new OptNilDetectedLabels with value set to v.
func NewOptNilDetectedLabels(v DetectedLabels) OptNilDetectedLabels {
	return OptNilDetectedLabels{
		Value: v,
		Set:   true,
	}
}

// OptNilDetectedLabels is optional nullable DetectedLabels.
type OptNilDetectedLabels struct {
	Value DetectedLabels
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDetectedLabels was set.
func (o OptNilDetectedLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDetectedLabels) Reset() {
	var v DetectedLabels
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDetectedLabels) SetTo(v DetectedLabels) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDetectedLabels) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDetectedLabels) SetToNull() {
	o.Set = true
	o.Null = true
	var v DetectedLabels
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDetectedLabels) Get() (v DetectedLabels, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDetectedLabels) Or(d DetectedLabels) DetectedLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilEnrichmentResults returns new OptNilEnrichmentResults with value set to v.
func NewOptNilEnrichmentResults(v EnrichmentResults) OptNilEnrichmentResults {
	return OptNilEnrichmentResults{
		Value: v,
		Set:   true,
	}
}

// OptNilEnrichmentResults is optional nullable EnrichmentResults.
type OptNilEnrichmentResults struct {
	Value EnrichmentResults
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilEnrichmentResults was set.
func (o OptNilEnrichmentResults) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilEnrichmentResults) Reset() {
	var v EnrichmentResults
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilEnrichmentResults) SetTo(v EnrichmentResults) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilEnrichmentResults) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilEnrichmentResults) SetToNull() {
	o.Set = true
	o.Null = true
	var v EnrichmentResults
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilEnrichmentResults) Get() (v EnrichmentResults, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilEnrichmentResults) Or(d EnrichmentResults) EnrichmentResults {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilEnrichmentResultsCustomLabels returns new OptNilEnrichmentResultsCustomLabels with value set to v.
func NewOptNilEnrichmentResultsCustomLabels(v EnrichmentResultsCustomLabels) OptNilEnrichmentResultsCustomLabels {
	return OptNilEnrichmentResultsCustomLabels{
		Value: v,
		Set:   true,
	}
}

// OptNilEnrichmentResultsCustomLabels is optional nullable EnrichmentResultsCustomLabels.
type OptNilEnrichmentResultsCustomLabels struct {
	Value EnrichmentResultsCustomLabels
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilEnrichmentResultsCustomLabels was set.
func (o OptNilEnrichmentResultsCustomLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilEnrichmentResultsCustomLabels) Reset() {
	var v EnrichmentResultsCustomLabels
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilEnrichmentResultsCustomLabels) SetTo(v EnrichmentResultsCustomLabels) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilEnrichmentResultsCustomLabels) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilEnrichmentResultsCustomLabels) SetToNull() {
	o.Set = true
	o.Null = true
	var v EnrichmentResultsCustomLabels
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilEnrichmentResultsCustomLabels) Get() (v EnrichmentResultsCustomLabels, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilEnrichmentResultsCustomLabels) Or(d EnrichmentResultsCustomLabels) EnrichmentResultsCustomLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilEnrichmentResultsKubernetesContext returns new OptNilEnrichmentResultsKubernetesContext with value set to v.
func NewOptNilEnrichmentResultsKubernetesContext(v EnrichmentResultsKubernetesContext) OptNilEnrichmentResultsKubernetesContext {
	return OptNilEnrichmentResultsKubernetesContext{
		Value: v,
		Set:   true,
	}
}

// OptNilEnrichmentResultsKubernetesContext is optional nullable EnrichmentResultsKubernetesContext.
type OptNilEnrichmentResultsKubernetesContext struct {
	Value EnrichmentResultsKubernetesContext
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilEnrichmentResultsKubernetesContext was set.
func (o OptNilEnrichmentResultsKubernetesContext) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilEnrichmentResultsKubernetesContext) Reset() {
	var v EnrichmentResultsKubernetesContext
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilEnrichmentResultsKubernetesContext) SetTo(v EnrichmentResultsKubernetesContext) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilEnrichmentResultsKubernetesContext) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilEnrichmentResultsKubernetesContext) SetToNull() {
	o.Set = true
	o.Null = true
	var v EnrichmentResultsKubernetesContext
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilEnrichmentResultsKubernetesContext) Get() (v EnrichmentResultsKubernetesContext, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilEnrichmentResultsKubernetesContext) Or(d EnrichmentResultsKubernetesContext) EnrichmentResultsKubernetesContext {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilIncidentRequestSignalLabels returns new OptNilIncidentRequestSignalLabels with value set to v.
func NewOptNilIncidentRequestSignalLabels(v IncidentRequestSignalLabels) OptNilIncidentRequestSignalLabels {
	return OptNilIncidentRequestSignalLabels{
		Value: v,
		Set:   true,
	}
}

// OptNilIncidentRequestSignalLabels is optional nullable IncidentRequestSignalLabels.
type OptNilIncidentRequestSignalLabels struct {
	Value IncidentRequestSignalLabels
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilIncidentRequestSignalLabels was set.
func (o OptNilIncidentRequestSignalLabels) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilIncidentRequestSignalLabels) Reset() {
	var v IncidentRequestSignalLabels
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilIncidentRequestSignalLabels) SetTo(v IncidentRequestSignalLabels) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilIncidentRequestSignalLabels) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilIncidentRequestSignalLabels) SetToNull() {
	o.Set = true
	o.Null = true
	var v IncidentRequestSignalLabels
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilIncidentRequestSignalLabels) Get() (v IncidentRequestSignalLabels, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilIncidentRequestSignalLabels) Or(d IncidentRequestSignalLabels) IncidentRequestSignalLabels {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilIncidentResponseSelectedWorkflow returns new OptNilIncidentResponseSelectedWorkflow with value set to v.
func NewOptNilIncidentResponseSelectedWorkflow(v IncidentResponseSelectedWorkflow) OptNilIncidentResponseSelectedWorkflow {
	return OptNilIncidentResponseSelectedWorkflow{
		Value: v,
		Set:   true,
	}
}

// OptNilIncidentResponseSelectedWorkflow is optional nullable IncidentResponseSelectedWorkflow.
type OptNilIncidentResponseSelectedWorkflow struct {
	Value IncidentResponseSelectedWorkflow
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilIncidentResponseSelectedWorkflow was set.
func (o OptNilIncidentResponseSelectedWorkflow) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilIncidentResponseSelectedWorkflow) Reset() {
	var v IncidentResponseSelectedWorkflow
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilIncidentResponseSelectedWorkflow) SetTo(v IncidentResponseSelectedWorkflow) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilIncidentResponseSelectedWorkflow) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilIncidentResponseSelectedWorkflow) SetToNull() {
	o.Set = true
	o.Null = true
	var v IncidentResponseSelectedWorkflow
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilIncidentResponseSelectedWorkflow) Get() (v IncidentResponseSelectedWorkflow, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilIncidentResponseSelectedWorkflow) Or(d IncidentResponseSelectedWorkflow) IncidentResponseSelectedWorkflow {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPostExecRequestContext returns new OptNilPostExecRequestContext with value set to v.
func NewOptNilPostExecRequestContext(v PostExecRequestContext) OptNilPostExecRequestContext {
	return OptNilPostExecRequestContext{
		Value: v,
		Set:   true,
	}
}

// OptNilPostExecRequestContext is optional nullable PostExecRequestContext.
type OptNilPostExecRequestContext struct {
	Value PostExecRequestContext
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPostExecRequestContext was set.
func (o OptNilPostExecRequestContext) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPostExecRequestContext) Reset() {
	var v PostExecRequestContext
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPostExecRequestContext) SetTo(v PostExecRequestContext) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPostExecRequestContext) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPostExecRequestContext) SetToNull() {
	o.Set = true
	o.Null = true
	var v PostExecRequestContext
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPostExecRequestContext) Get() (v PostExecRequestContext, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPostExecRequestContext) Or(d PostExecRequestContext) PostExecRequestContext {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPostExecRequestPostExecutionState returns new OptNilPostExecRequestPostExecutionState with value set to v.
func NewOptNilPostExecRequestPostExecutionState(v PostExecRequestPostExecutionState) OptNilPostExecRequestPostExecutionState {
	return OptNilPostExecRequestPostExecutionState{
		Value: v,
		Set:   true,
	}
}

// OptNilPostExecRequestPostExecutionState is optional nullable PostExecRequestPostExecutionState.
type OptNilPostExecRequestPostExecutionState struct {
	Value PostExecRequestPostExecutionState
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPostExecRequestPostExecutionState was set.
func (o OptNilPostExecRequestPostExecutionState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPostExecRequestPostExecutionState) Reset() {
	var v PostExecRequestPostExecutionState
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPostExecRequestPostExecutionState) SetTo(v PostExecRequestPostExecutionState) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPostExecRequestPostExecutionState) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPostExecRequestPostExecutionState) SetToNull() {
	o.Set = true
	o.Null = true
	var v PostExecRequestPostExecutionState
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPostExecRequestPostExecutionState) Get() (v PostExecRequestPostExecutionState, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPostExecRequestPostExecutionState) Or(d PostExecRequestPostExecutionState) PostExecRequestPostExecutionState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPostExecRequestPreExecutionState returns new OptNilPostExecRequestPreExecutionState with value set to v.
func NewOptNilPostExecRequestPreExecutionState(v PostExecRequestPreExecutionState) OptNilPostExecRequestPreExecutionState {
	return OptNilPostExecRequestPreExecutionState{
		Value: v,
		Set:   true,
	}
}

// OptNilPostExecRequestPreExecutionState is optional nullable PostExecRequestPreExecutionState.
type OptNilPostExecRequestPreExecutionState struct {
	Value PostExecRequestPreExecutionState
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPostExecRequestPreExecutionState was set.
func (o OptNilPostExecRequestPreExecutionState) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPostExecRequestPreExecutionState) Reset() {
	var v PostExecRequestPreExecutionState
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPostExecRequestPreExecutionState) SetTo(v PostExecRequestPreExecutionState) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPostExecRequestPreExecutionState) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPostExecRequestPreExecutionState) SetToNull() {
	o.Set = true
	o.Null = true
	var v PostExecRequestPreExecutionState
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPostExecRequestPreExecutionState) Get() (v PostExecRequestPreExecutionState, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPostExecRequestPreExecutionState) Or(d PostExecRequestPreExecutionState) PostExecRequestPreExecutionState {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilPreviousExecution returns new OptNilPreviousExecution with value set to v.
func NewOptNilPreviousExecution(v PreviousExecution) OptNilPreviousExecution {
	return OptNilPreviousExecution{
		Value: v,
		Set:   true,
	}
}

// OptNilPreviousExecution is optional nullable PreviousExecution.
type OptNilPreviousExecution struct {
	Value PreviousExecution
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilPreviousExecution was set.
func (o OptNilPreviousExecution) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilPreviousExecution) Reset() {
	var v PreviousExecution
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilPreviousExecution) SetTo(v PreviousExecution) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilPreviousExecution) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilPreviousExecution) SetToNull() {
	o.Set = true
	o.Null = true
	var v PreviousExecution
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilPreviousExecution) Get() (v PreviousExecution, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilPreviousExecution) Or(d PreviousExecution) PreviousExecution {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilRecoveryRequestEnrichmentResults returns new OptNilRecoveryRequestEnrichmentResults with value set to v.
func NewOptNilRecoveryRequestEnrichmentResults(v RecoveryRequestEnrichmentResults) OptNilRecoveryRequestEnrichmentResults {
	return OptNilRecoveryRequestEnrichmentResults{
		Value: v,
		Set:   true,
	}
}

// OptNilRecoveryRequestEnrichmentResults is optional nullable RecoveryRequestEnrichmentResults.
type OptNilRecoveryRequestEnrichmentResults struct {
	Value RecoveryRequestEnrichmentResults
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilRecoveryRequestEnrichmentResults was set.
func (o OptNilRecoveryRequestEnrichmentResults) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilRecoveryRequestEnrichmentResults) Reset() {
	var v RecoveryRequestEnrichmentResults
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilRecoveryRequestEnrichmentResults) SetTo(v RecoveryRequestEnrichmentResults) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilRecoveryRequestEnrichmentResults) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilRecoveryRequestEnrichmentResults) SetToNull() {
	o.Set = true
	o.Null = true
	var v RecoveryRequestEnrichmentResults
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilRecoveryRequestEnrichmentResults) Get() (v RecoveryRequestEnrichmentResults, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilRecoveryRequestEnrichmentResults) Or(d RecoveryRequestEnrichmentResults) RecoveryRequestEnrichmentResults {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilStringArray returns new OptNilStringArray with value set to v.
func NewOptNilStringArray(v []string) OptNilStringArray {
	return OptNilStringArray{
		Value: v,
		Set:   true,
	}
}

// OptNilStringArray is optional nullable []string.
type OptNilStringArray struct {
	Value []string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilStringArray was set.
func (o OptNilStringArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilStringArray) Reset() {
	var v []string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilStringArray) SetTo(v []string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilStringArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilStringArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilStringArray) Get() (v []string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilStringArray) Or(d []string) []string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPostExecResponseMetadata returns new OptPostExecResponseMetadata with value set to v.
func NewOptPostExecResponseMetadata(v PostExecResponseMetadata) OptPostExecResponseMetadata {
	return OptPostExecResponseMetadata{
		Value: v,
		Set:   true,
	}
}

// OptPostExecResponseMetadata is optional PostExecResponseMetadata.
type OptPostExecResponseMetadata struct {
	Value PostExecResponseMetadata
	Set   bool
}

// IsSet returns true if OptPostExecResponseMetadata was set.
func (o OptPostExecResponseMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPostExecResponseMetadata) Reset() {
	var v PostExecResponseMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPostExecResponseMetadata) SetTo(v PostExecResponseMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPostExecResponseMetadata) Get() (v PostExecResponseMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPostExecResponseMetadata) Or(d PostExecResponseMetadata) PostExecResponseMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRecoveryResponseMetadata returns new OptRecoveryResponseMetadata with value set to v.
func NewOptRecoveryResponseMetadata(v RecoveryResponseMetadata) OptRecoveryResponseMetadata {
	return OptRecoveryResponseMetadata{
		Value: v,
		Set:   true,
	}
}

// OptRecoveryResponseMetadata is optional RecoveryResponseMetadata.
type OptRecoveryResponseMetadata struct {
	Value RecoveryResponseMetadata
	Set   bool
}

// IsSet returns true if OptRecoveryResponseMetadata was set.
func (o OptRecoveryResponseMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRecoveryResponseMetadata) Reset() {
	var v RecoveryResponseMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRecoveryResponseMetadata) SetTo(v RecoveryResponseMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRecoveryResponseMetadata) Get() (v RecoveryResponseMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRecoveryResponseMetadata) Or(d RecoveryResponseMetadata) RecoveryResponseMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSelectedWorkflowSummaryParameters returns new OptSelectedWorkflowSummaryParameters with value set to v.
func NewOptSelectedWorkflowSummaryParameters(v SelectedWorkflowSummaryParameters) OptSelectedWorkflowSummaryParameters {
	return OptSelectedWorkflowSummaryParameters{
		Value: v,
		Set:   true,
	}
}

// OptSelectedWorkflowSummaryParameters is optional SelectedWorkflowSummaryParameters.
type OptSelectedWorkflowSummaryParameters struct {
	Value SelectedWorkflowSummaryParameters
	Set   bool
}

// IsSet returns true if OptSelectedWorkflowSummaryParameters was set.
func (o OptSelectedWorkflowSummaryParameters) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSelectedWorkflowSummaryParameters) Reset() {
	var v SelectedWorkflowSummaryParameters
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSelectedWorkflowSummaryParameters) SetTo(v SelectedWorkflowSummaryParameters) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSelectedWorkflowSummaryParameters) Get() (v SelectedWorkflowSummaryParameters, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSelectedWorkflowSummaryParameters) Or(d SelectedWorkflowSummaryParameters) SelectedWorkflowSummaryParameters {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Summary of the original root cause analysis from initial AIAnalysis.
// Ref: #/components/schemas/OriginalRCA
type OriginalRCA struct {
	// Brief RCA summary from initial investigation.
	Summary string `json:"summary"`
	// Signal type determined by original RCA (e.g., 'OOMKilled').
	SignalType string `json:"signal_type"`
	// Severity determined by original RCA.
	Severity string `json:"severity"`
	// Factors that contributed to the issue.
	ContributingFactors []string `json:"contributing_factors"`
}

// GetSummary returns the value of Summary.
func (s *OriginalRCA) GetSummary() string {
	return s.Summary
}

// GetSignalType returns the value of SignalType.
func (s *OriginalRCA) GetSignalType() string {
	return s.SignalType
}

// GetSeverity returns the value of Severity.
func (s *OriginalRCA) GetSeverity() string {
	return s.Severity
}

// GetContributingFactors returns the value of ContributingFactors.
func (s *OriginalRCA) GetContributingFactors() []string {
	return s.ContributingFactors
}

// SetSummary sets the value of Summary.
func (s *OriginalRCA) SetSummary(val string) {
	s.Summary = val
}

// SetSignalType sets the value of SignalType.
func (s *OriginalRCA) SetSignalType(val string) {
	s.SignalType = val
}

// SetSeverity sets the value of Severity.
func (s *OriginalRCA) SetSeverity(val string) {
	s.Severity = val
}

// SetContributingFactors sets the value of ContributingFactors.
func (s *OriginalRCA) SetContributingFactors(val []string) {
	s.ContributingFactors = val
}

// Request model for post-execution analysis endpoint
// Business Requirement: BR-HAPI-051 (Post-exec request schema).
// Ref: #/components/schemas/PostExecRequest
type PostExecRequest struct {
	// Unique execution identifier.
	ExecutionID string `json:"execution_id"`
	// Action that was executed.
	ActionID string `json:"action_id"`
	// Type of action executed.
	ActionType string `json:"action_type"`
	// Details of executed action.
	ActionDetails PostExecRequestActionDetails `json:"action_details"`
	// Whether execution completed without errors.
	ExecutionSuccess bool `json:"execution_success"`
	// Technical execution results.
	ExecutionResult PostExecRequestExecutionResult `json:"execution_result"`
	// State before execution.
	PreExecutionState OptNilPostExecRequestPreExecutionState `json:"pre_execution_state"`
	// State after execution.
	PostExecutionState OptNilPostExecRequestPostExecutionState `json:"post_execution_state"`
	// Additional context.
	Context OptNilPostExecRequestContext `json:"context"`
}

// GetExecutionID returns the value of ExecutionID.
func (s *PostExecRequest) GetExecutionID() string {
	return s.ExecutionID
}

// GetActionID returns the value of ActionID.
func (s *PostExecRequest) GetActionID() string {
	return s.ActionID
}

// GetActionType returns the value of ActionType.
func (s *PostExecRequest) GetActionType() string {
	return s.ActionType
}

// GetActionDetails returns the value of ActionDetails.
func (s *PostExecRequest) GetActionDetails() PostExecRequestActionDetails {
	return s.ActionDetails
}

// GetExecutionSuccess returns the value of ExecutionSuccess.
func (s *PostExecRequest) GetExecutionSuccess() bool {
	return s.ExecutionSuccess
}

// GetExecutionResult returns the value of ExecutionResult.
func (s *PostExecRequest) GetExecutionResult() PostExecRequestExecutionResult {
	return s.ExecutionResult
}

// GetPreExecutionState returns the value of PreExecutionState.
func (s *PostExecRequest) GetPreExecutionState() OptNilPostExecRequestPreExecutionState {
	return s.PreExecutionState
}

// GetPostExecutionState returns the value of PostExecutionState.
func (s *PostExecRequest) GetPostExecutionState() OptNilPostExecRequestPostExecutionState {
	return s.PostExecutionState
}

// GetContext returns the value of Context.
func (s *PostExecRequest) GetContext() OptNilPostExecRequestContext {
	return s.Context
}

// SetExecutionID sets the value of ExecutionID.
func (s *PostExecRequest) SetExecutionID(val string) {
	s.ExecutionID = val
}

// SetActionID sets the value of ActionID.
func (s *PostExecRequest) SetActionID(val string) {
	s.ActionID = val
}

// SetActionType sets the value of ActionType.
func (s *PostExecRequest) SetActionType(val string) {
	s.ActionType = val
}

// SetActionDetails sets the value of ActionDetails.
func (s *PostExecRequest) SetActionDetails(val PostExecRequestActionDetails) {
	s.ActionDetails = val
}

// SetExecutionSuccess sets the value of ExecutionSuccess.
func (s *PostExecRequest) SetExecutionSuccess(val bool) {
	s.ExecutionSuccess = val
}

// SetExecutionResult sets the value of ExecutionResult.
func (s *PostExecRequest) SetExecutionResult(val PostExecRequestExecutionResult) {
	s.ExecutionResult = val
}

// SetPreExecutionState sets the value of PreExecutionState.
func (s *PostExecRequest) SetPreExecutionState(val OptNilPostExecRequestPreExecutionState) {
	s.PreExecutionState = val
}

// SetPostExecutionState sets the value of PostExecutionState.
func (s *PostExecRequest) SetPostExecutionState(val OptNilPostExecRequestPostExecutionState) {
	s.PostExecutionState = val
}

// SetContext sets the value of Context.
func (s *PostExecRequest) SetContext(val OptNilPostExecRequestContext) {
	s.Context = val
}

// Details of executed action.
type PostExecRequestActionDetails map[string]jx.Raw

func (s *PostExecRequestActionDetails) init() PostExecRequestActionDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PostExecRequestContext map[string]jx.Raw

func (s *PostExecRequestContext) init() PostExecRequestContext {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Technical execution results.
type PostExecRequestExecutionResult map[string]jx.Raw

func (s *PostExecRequestExecutionResult) init() PostExecRequestExecutionResult {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PostExecRequestPostExecutionState map[string]jx.Raw

func (s *PostExecRequestPostExecutionState) init() PostExecRequestPostExecutionState {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PostExecRequestPreExecutionState map[string]jx.Raw

func (s *PostExecRequestPreExecutionState) init() PostExecRequestPreExecutionState {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Response model for post-execution analysis endpoint
// Business Requirement: BR-HAPI-052 (Post-exec response schema).
// Ref: #/components/schemas/PostExecResponse
type PostExecResponse struct {
	// Execution identifier from request.
	ExecutionID string `json:"execution_id"`
	// Effectiveness assessment.
	Effectiveness EffectivenessAssessment `json:"effectiveness"`
	// Whether objectives were met.
	ObjectivesMet bool `json:"objectives_met"`
	// Detected side effects.
	SideEffects []string `json:"side_effects"`
	// Recommendations for improvement.
	Recommendations []string `json:"recommendations"`
	// Pattern learning data.
	PatternImprovements []PostExecResponsePatternImprovementsItem `json:"pattern_improvements"`
	// Additional metadata.
	Metadata OptPostExecResponseMetadata `json:"metadata"`
}

// GetExecutionID returns the value of ExecutionID.
func (s *PostExecResponse) GetExecutionID() string {
	return s.ExecutionID
}

// GetEffectiveness returns the value of Effectiveness.
func (s *PostExecResponse) GetEffectiveness() EffectivenessAssessment {
	return s.Effectiveness
}

// GetObjectivesMet returns the value of ObjectivesMet.
func (s *PostExecResponse) GetObjectivesMet() bool {
	return s.ObjectivesMet
}

// GetSideEffects returns the value of SideEffects.
func (s *PostExecResponse) GetSideEffects() []string {
	return s.SideEffects
}

// GetRecommendations returns the value of Recommendations.
func (s *PostExecResponse) GetRecommendations() []string {
	return s.Recommendations
}

// GetPatternImprovements returns the value of PatternImprovements.
func (s *PostExecResponse) GetPatternImprovements() []PostExecResponsePatternImprovementsItem {
	return s.PatternImprovements
}

// GetMetadata returns the value of Metadata.
func (s *PostExecResponse) GetMetadata() OptPostExecResponseMetadata {
	return s.Metadata
}

// SetExecutionID sets the value of ExecutionID.
func (s *PostExecResponse) SetExecutionID(val string) {
	s.ExecutionID = val
}

// SetEffectiveness sets the value of Effectiveness.
func (s *PostExecResponse) SetEffectiveness(val EffectivenessAssessment) {
	s.Effectiveness = val
}

// SetObjectivesMet sets the value of ObjectivesMet.
func (s *PostExecResponse) SetObjectivesMet(val bool) {
	s.ObjectivesMet = val
}

// SetSideEffects sets the value of SideEffects.
func (s *PostExecResponse) SetSideEffects(val []string) {
	s.SideEffects = val
}

// SetRecommendations sets the value of Recommendations.
func (s *PostExecResponse) SetRecommendations(val []string) {
	s.Recommendations = val
}

// SetPatternImprovements sets the value of PatternImprovements.
func (s *PostExecResponse) SetPatternImprovements(val []PostExecResponsePatternImprovementsItem) {
	s.PatternImprovements = val
}

// SetMetadata sets the value of Metadata.
func (s *PostExecResponse) SetMetadata(val OptPostExecResponseMetadata) {
	s.Metadata = val
}

func (*PostExecResponse) postexecAnalyzeEndpointAPIV1PostexecAnalyzePostRes() {}

// Additional metadata.
type PostExecResponseMetadata map[string]jx.Raw

func (s *PostExecResponseMetadata) init() PostExecResponseMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type PostExecResponsePatternImprovementsItem map[string]jx.Raw

func (s *PostExecResponsePatternImprovementsItem) init() PostExecResponsePatternImprovementsItem {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Complete context about the previous execution attempt that failed.
// Ref: #/components/schemas/PreviousExecution
type PreviousExecution struct {
	// Name of failed WorkflowExecution CRD.
	WorkflowExecutionRef string `json:"workflow_execution_ref"`
	// RCA from initial AIAnalysis.
	OriginalRca OriginalRCA `json:"original_rca"`
	// Workflow that was executed.
	SelectedWorkflow SelectedWorkflowSummary `json:"selected_workflow"`
	// Structured failure details.
	Failure ExecutionFailure `json:"failure"`
}

// GetWorkflowExecutionRef returns the value of WorkflowExecutionRef.
func (s *PreviousExecution) GetWorkflowExecutionRef() string {
	return s.WorkflowExecutionRef
}

// GetOriginalRca returns the value of OriginalRca.
func (s *PreviousExecution) GetOriginalRca() OriginalRCA {
	return s.OriginalRca
}

// GetSelectedWorkflow returns the value of SelectedWorkflow.
func (s *PreviousExecution) GetSelectedWorkflow() SelectedWorkflowSummary {
	return s.SelectedWorkflow
}

// GetFailure returns the value of Failure.
func (s *PreviousExecution) GetFailure() ExecutionFailure {
	return s.Failure
}

// SetWorkflowExecutionRef sets the value of WorkflowExecutionRef.
func (s *PreviousExecution) SetWorkflowExecutionRef(val string) {
	s.WorkflowExecutionRef = val
}

// SetOriginalRca sets the value of OriginalRca.
func (s *PreviousExecution) SetOriginalRca(val OriginalRCA) {
	s.OriginalRca = val
}

// SetSelectedWorkflow sets the value of SelectedWorkflow.
func (s *PreviousExecution) SetSelectedWorkflow(val SelectedWorkflowSummary) {
	s.SelectedWorkflow = val
}

// SetFailure sets the value of Failure.
func (s *PreviousExecution) SetFailure(val ExecutionFailure) {
	s.Failure = val
}

// Request model for recovery analysis endpoint
// Business Requirements:
// - BR-HAPI-001: Recovery request schema
// - BR-AUDIT-001: Unified audit trail (remediation_id)
// Design Decision: DD-WORKFLOW-002 v2.2
// - remediation_id is MANDATORY for audit trail correlation
// - remediation_id is for CORRELATION ONLY - do NOT use for RCA or workflow matching
// Design Decision: DD-RECOVERY-002, DD-RECOVERY-003
// - Structured PreviousExecution for recovery attempts
// - is_recovery_attempt and recovery_attempt_number for tracking
// - enrichment_results for DetectedLabels workflow filtering.
// Ref: #/components/schemas/RecoveryRequest
type RecoveryRequest struct {
	// Unique incident identifier.
	IncidentID string `json:"incident_id"`
	// Remediation request ID for audit correlation (e.g., 'req-2025-11-27-abc123'). MANDATORY per
	// DD-WORKFLOW-002 v2.2. This ID is for CORRELATION/AUDIT ONLY - do NOT use for RCA analysis or
	// workflow matching.
	RemediationID string `json:"remediation_id"`
	// True if this is a recovery attempt after failed workflow.
	IsRecoveryAttempt OptBool `json:"is_recovery_attempt"`
	// Which recovery attempt this is (1, 2, 3...).
	RecoveryAttemptNumber OptNilInt `json:"recovery_attempt_number"`
	// Context from previous failed attempt.
	PreviousExecution OptNilPreviousExecution `json:"previous_execution"`
	// Enriched context including DetectedLabels for workflow filtering.
	EnrichmentResults OptNilRecoveryRequestEnrichmentResults `json:"enrichment_results"`
	// Current signal type (may have changed).
	SignalType OptNilString `json:"signal_type"`
	// Current severity.
	Severity OptNilString `json:"severity"`
	// Kubernetes namespace.
	ResourceNamespace OptNilString `json:"resource_namespace"`
	// Kubernetes resource kind.
	ResourceKind OptNilString `json:"resource_kind"`
	// Kubernetes resource name.
	ResourceName OptNilString `json:"resource_name"`
	// Environment classification.
	Environment OptString `json:"environment"`
	// Priority level.
	Priority OptString `json:"priority"`
	// Risk tolerance.
	RiskTolerance OptString `json:"risk_tolerance"`
	// Business category.
	BusinessCategory OptString `json:"business_category"`
	// Current error message.
	ErrorMessage OptNilString `json:"error_message"`
	// Cluster name.
	ClusterName OptNilString `json:"cluster_name"`
	// Signal source.
	SignalSource OptNilString `json:"signal_source"`
}

// GetIncidentID returns the value of IncidentID.
func (s *RecoveryRequest) GetIncidentID() string {
	return s.IncidentID
}

// GetRemediationID returns the value of RemediationID.
func (s *RecoveryRequest) GetRemediationID() string {
	return s.RemediationID
}

// GetIsRecoveryAttempt returns the value of IsRecoveryAttempt.
func (s *RecoveryRequest) GetIsRecoveryAttempt() OptBool {
	return s.IsRecoveryAttempt
}

// GetRecoveryAttemptNumber returns the value of RecoveryAttemptNumber.
func (s *RecoveryRequest) GetRecoveryAttemptNumber() OptNilInt {
	return s.RecoveryAttemptNumber
}

// GetPreviousExecution returns the value of PreviousExecution.
func (s *RecoveryRequest) GetPreviousExecution() OptNilPreviousExecution {
	return s.PreviousExecution
}

// GetEnrichmentResults returns the value of EnrichmentResults.
func (s *RecoveryRequest) GetEnrichmentResults() OptNilRecoveryRequestEnrichmentResults {
	return s.EnrichmentResults
}

// GetSignalType returns the value of SignalType.
func (s *RecoveryRequest) GetSignalType() OptNilString {
	return s.SignalType
}

// GetSeverity returns the value of Severity.
func (s *RecoveryRequest) GetSeverity() OptNilString {
	return s.Severity
}

// GetResourceNamespace returns the value of ResourceNamespace.
func (s *RecoveryRequest) GetResourceNamespace() OptNilString {
	return s.ResourceNamespace
}

// GetResourceKind returns the value of ResourceKind.
func (s *RecoveryRequest) GetResourceKind() OptNilString {
	return s.ResourceKind
}

// GetResourceName returns the value of ResourceName.
func (s *RecoveryRequest) GetResourceName() OptNilString {
	return s.ResourceName
}

// GetEnvironment returns the value of Environment.
func (s *RecoveryRequest) GetEnvironment() OptString {
	return s.Environment
}

// GetPriority returns the value of Priority.
func (s *RecoveryRequest) GetPriority() OptString {
	return s.Priority
}

// GetRiskTolerance returns the value of RiskTolerance.
func (s *RecoveryRequest) GetRiskTolerance() OptString {
	return s.RiskTolerance
}

// GetBusinessCategory returns the value of BusinessCategory.
func (s *RecoveryRequest) GetBusinessCategory() OptString {
	return s.BusinessCategory
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *RecoveryRequest) GetErrorMessage() OptNilString {
	return s.ErrorMessage
}

// GetClusterName returns the value of ClusterName.
func (s *RecoveryRequest) GetClusterName() OptNilString {
	return s.ClusterName
}

// GetSignalSource returns the value of SignalSource.
func (s *RecoveryRequest) GetSignalSource() OptNilString {
	return s.SignalSource
}

// SetIncidentID sets the value of IncidentID.
func (s *RecoveryRequest) SetIncidentID(val string) {
	s.IncidentID = val
}

// SetRemediationID sets the value of RemediationID.
func (s *RecoveryRequest) SetRemediationID(val string) {
	s.RemediationID = val
}

// SetIsRecoveryAttempt sets the value of IsRecoveryAttempt.
func (s *RecoveryRequest) SetIsRecoveryAttempt(val OptBool) {
	s.IsRecoveryAttempt = val
}

// SetRecoveryAttemptNumber sets the value of RecoveryAttemptNumber.
func (s *RecoveryRequest) SetRecoveryAttemptNumber(val OptNilInt) {
	s.RecoveryAttemptNumber = val
}

// SetPreviousExecution sets the value of PreviousExecution.
func (s *RecoveryRequest) SetPreviousExecution(val OptNilPreviousExecution) {
	s.PreviousExecution = val
}

// SetEnrichmentResults sets the value of EnrichmentResults.
func (s *RecoveryRequest) SetEnrichmentResults(val OptNilRecoveryRequestEnrichmentResults) {
	s.EnrichmentResults = val
}

// SetSignalType sets the value of SignalType.
func (s *RecoveryRequest) SetSignalType(val OptNilString) {
	s.SignalType = val
}

// SetSeverity sets the value of Severity.
func (s *RecoveryRequest) SetSeverity(val OptNilString) {
	s.Severity = val
}

// SetResourceNamespace sets the value of ResourceNamespace.
func (s *RecoveryRequest) SetResourceNamespace(val OptNilString) {
	s.ResourceNamespace = val
}

// SetResourceKind sets the value of ResourceKind.
func (s *RecoveryRequest) SetResourceKind(val OptNilString) {
	s.ResourceKind = val
}

// SetResourceName sets the value of ResourceName.
func (s *RecoveryRequest) SetResourceName(val OptNilString) {
	s.ResourceName = val
}

// SetEnvironment sets the value of Environment.
func (s *RecoveryRequest) SetEnvironment(val OptString) {
	s.Environment = val
}

// SetPriority sets the value of Priority.
func (s *RecoveryRequest) SetPriority(val OptString) {
	s.Priority = val
}

// SetRiskTolerance sets the value of RiskTolerance.
func (s *RecoveryRequest) SetRiskTolerance(val OptString) {
	s.RiskTolerance = val
}

// SetBusinessCategory sets the value of BusinessCategory.
func (s *RecoveryRequest) SetBusinessCategory(val OptString) {
	s.BusinessCategory = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *RecoveryRequest) SetErrorMessage(val OptNilString) {
	s.ErrorMessage = val
}

// SetClusterName sets the value of ClusterName.
func (s *RecoveryRequest) SetClusterName(val OptNilString) {
	s.ClusterName = val
}

// SetSignalSource sets the value of SignalSource.
func (s *RecoveryRequest) SetSignalSource(val OptNilString) {
	s.SignalSource = val
}

type RecoveryRequestEnrichmentResults map[string]jx.Raw

func (s *RecoveryRequestEnrichmentResults) init() RecoveryRequestEnrichmentResults {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Response model for recovery analysis endpoint
// Business Requirement: BR-HAPI-002 (Recovery response schema).
// Ref: #/components/schemas/RecoveryResponse
type RecoveryResponse struct {
	// Incident identifier from request.
	IncidentID string `json:"incident_id"`
	// Whether recovery is possible.
	CanRecover bool `json:"can_recover"`
	// Recommended recovery strategies.
	Strategies []RecoveryStrategy `json:"strategies"`
	// Primary recovery action type.
	PrimaryRecommendation OptNilString `json:"primary_recommendation"`
	// Overall confidence.
	AnalysisConfidence float64 `json:"analysis_confidence"`
	// Warnings about recovery.
	Warnings []string `json:"warnings"`
	// Additional metadata.
	Metadata OptRecoveryResponseMetadata `json:"metadata"`
}

// GetIncidentID returns the value of IncidentID.
func (s *RecoveryResponse) GetIncidentID() string {
	return s.IncidentID
}

// GetCanRecover returns the value of CanRecover.
func (s *RecoveryResponse) GetCanRecover() bool {
	return s.CanRecover
}

// GetStrategies returns the value of Strategies.
func (s *RecoveryResponse) GetStrategies() []RecoveryStrategy {
	return s.Strategies
}

// GetPrimaryRecommendation returns the value of PrimaryRecommendation.
func (s *RecoveryResponse) GetPrimaryRecommendation() OptNilString {
	return s.PrimaryRecommendation
}

// GetAnalysisConfidence returns the value of AnalysisConfidence.
func (s *RecoveryResponse) GetAnalysisConfidence() float64 {
	return s.AnalysisConfidence
}

// GetWarnings returns the value of Warnings.
func (s *RecoveryResponse) GetWarnings() []string {
	return s.Warnings
}

// GetMetadata returns the value of Metadata.
func (s *RecoveryResponse) GetMetadata() OptRecoveryResponseMetadata {
	return s.Metadata
}

// SetIncidentID sets the value of IncidentID.
func (s *RecoveryResponse) SetIncidentID(val string) {
	s.IncidentID = val
}

// SetCanRecover sets the value of CanRecover.
func (s *RecoveryResponse) SetCanRecover(val bool) {
	s.CanRecover = val
}

// SetStrategies sets the value of Strategies.
func (s *RecoveryResponse) SetStrategies(val []RecoveryStrategy) {
	s.Strategies = val
}

// SetPrimaryRecommendation sets the value of PrimaryRecommendation.
func (s *RecoveryResponse) SetPrimaryRecommendation(val OptNilString) {
	s.PrimaryRecommendation = val
}

// SetAnalysisConfidence sets the value of AnalysisConfidence.
func (s *RecoveryResponse) SetAnalysisConfidence(val float64) {
	s.AnalysisConfidence = val
}

// SetWarnings sets the value of Warnings.
func (s *RecoveryResponse) SetWarnings(val []string) {
	s.Warnings = val
}

// SetMetadata sets the value of Metadata.
func (s *RecoveryResponse) SetMetadata(val OptRecoveryResponseMetadata) {
	s.Metadata = val
}

func (*RecoveryResponse) recoveryAnalyzeEndpointAPIV1RecoveryAnalyzePostRes() {}

// Additional metadata.
type RecoveryResponseMetadata map[string]jx.Raw

func (s *RecoveryResponseMetadata) init() RecoveryResponseMetadata {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Individual recovery strategy option.
// Ref: #/components/schemas/RecoveryStrategy
type RecoveryStrategy struct {
	// Type of recovery action.
	ActionType string `json:"action_type"`
	// Confidence in strategy.
	Confidence float64 `json:"confidence"`
	// Why this strategy is recommended.
	Rationale string `json:"rationale"`
	// Risk level.
	EstimatedRisk RecoveryStrategyEstimatedRisk `json:"estimated_risk"`
	// Prerequisites for execution.
	Prerequisites []string `json:"prerequisites"`
}

// GetActionType returns the value of ActionType.
func (s *RecoveryStrategy) GetActionType() string {
	return s.ActionType
}

// GetConfidence returns the value of Confidence.
func (s *RecoveryStrategy) GetConfidence() float64 {
	return s.Confidence
}

// GetRationale returns the value of Rationale.
func (s *RecoveryStrategy) GetRationale() string {
	return s.Rationale
}

// GetEstimatedRisk returns the value of EstimatedRisk.
func (s *RecoveryStrategy) GetEstimatedRisk() RecoveryStrategyEstimatedRisk {
	return s.EstimatedRisk
}

// GetPrerequisites returns the value of Prerequisites.
func (s *RecoveryStrategy) GetPrerequisites() []string {
	return s.Prerequisites
}

// SetActionType sets the value of ActionType.
func (s *RecoveryStrategy) SetActionType(val string) {
	s.ActionType = val
}

// SetConfidence sets the value of Confidence.
func (s *RecoveryStrategy) SetConfidence(val float64) {
	s.Confidence = val
}

// SetRationale sets the value of Rationale.
func (s *RecoveryStrategy) SetRationale(val string) {
	s.Rationale = val
}

// SetEstimatedRisk sets the value of EstimatedRisk.
func (s *RecoveryStrategy) SetEstimatedRisk(val RecoveryStrategyEstimatedRisk) {
	s.EstimatedRisk = val
}

// SetPrerequisites sets the value of Prerequisites.
func (s *RecoveryStrategy) SetPrerequisites(val []string) {
	s.Prerequisites = val
}

// Risk level.
type RecoveryStrategyEstimatedRisk string

const (
	RecoveryStrategyEstimatedRiskLow    RecoveryStrategyEstimatedRisk = "low"
	RecoveryStrategyEstimatedRiskMedium RecoveryStrategyEstimatedRisk = "medium"
	RecoveryStrategyEstimatedRiskHigh   RecoveryStrategyEstimatedRisk = "high"
)

// AllValues returns all RecoveryStrategyEstimatedRisk values.
func (RecoveryStrategyEstimatedRisk) AllValues() []RecoveryStrategyEstimatedRisk {
	return []RecoveryStrategyEstimatedRisk{
		RecoveryStrategyEstimatedRiskLow,
		RecoveryStrategyEstimatedRiskMedium,
		RecoveryStrategyEstimatedRiskHigh,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RecoveryStrategyEstimatedRisk) MarshalText() ([]byte, error) {
	switch s {
	case RecoveryStrategyEstimatedRiskLow:
		return []byte(s), nil
	case RecoveryStrategyEstimatedRiskMedium:
		return []byte(s), nil
	case RecoveryStrategyEstimatedRiskHigh:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RecoveryStrategyEstimatedRisk) UnmarshalText(data []byte) error {
	switch RecoveryStrategyEstimatedRisk(data) {
	case RecoveryStrategyEstimatedRiskLow:
		*s = RecoveryStrategyEstimatedRiskLow
		return nil
	case RecoveryStrategyEstimatedRiskMedium:
		*s = RecoveryStrategyEstimatedRiskMedium
		return nil
	case RecoveryStrategyEstimatedRiskHigh:
		*s = RecoveryStrategyEstimatedRiskHigh
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Summary of the workflow that was executed and failed.
// Ref: #/components/schemas/SelectedWorkflowSummary
type SelectedWorkflowSummary struct {
	// Workflow identifier that was executed.
	WorkflowID string `json:"workflow_id"`
	// Workflow version.
	Version string `json:"version"`
	// Container image used for execution.
	ContainerImage string `json:"container_image"`
	// Parameters passed to workflow.
	Parameters OptSelectedWorkflowSummaryParameters `json:"parameters"`
	// Why this workflow was originally selected.
	Rationale string `json:"rationale"`
}

// GetWorkflowID returns the value of WorkflowID.
func (s *SelectedWorkflowSummary) GetWorkflowID() string {
	return s.WorkflowID
}

// GetVersion returns the value of Version.
func (s *SelectedWorkflowSummary) GetVersion() string {
	return s.Version
}

// GetContainerImage returns the value of ContainerImage.
func (s *SelectedWorkflowSummary) GetContainerImage() string {
	return s.ContainerImage
}

// GetParameters returns the value of Parameters.
func (s *SelectedWorkflowSummary) GetParameters() OptSelectedWorkflowSummaryParameters {
	return s.Parameters
}

// GetRationale returns the value of Rationale.
func (s *SelectedWorkflowSummary) GetRationale() string {
	return s.Rationale
}

// SetWorkflowID sets the value of WorkflowID.
func (s *SelectedWorkflowSummary) SetWorkflowID(val string) {
	s.WorkflowID = val
}

// SetVersion sets the value of Version.
func (s *SelectedWorkflowSummary) SetVersion(val string) {
	s.Version = val
}

// SetContainerImage sets the value of ContainerImage.
func (s *SelectedWorkflowSummary) SetContainerImage(val string) {
	s.ContainerImage = val
}

// SetParameters sets the value of Parameters.
func (s *SelectedWorkflowSummary) SetParameters(val OptSelectedWorkflowSummaryParameters) {
	s.Parameters = val
}

// SetRationale sets the value of Rationale.
func (s *SelectedWorkflowSummary) SetRationale(val string) {
	s.Rationale = val
}

// Parameters passed to workflow.
type SelectedWorkflowSummaryParameters map[string]string

func (s *SelectedWorkflowSummaryParameters) init() SelectedWorkflowSummaryParameters {
	m := *s
	if m == nil {
		m = map[string]string{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/ValidationError
type ValidationError struct {
	Loc  []ValidationErrorLocItem `json:"loc"`
	Msg  string                   `json:"msg"`
	Type string                   `json:"type"`
}

// GetLoc returns the value of Loc.
func (s *ValidationError) GetLoc() []ValidationErrorLocItem {
	return s.Loc
}

// GetMsg returns the value of Msg.
func (s *ValidationError) GetMsg() string {
	return s.Msg
}

// GetType returns the value of Type.
func (s *ValidationError) GetType() string {
	return s.Type
}

// SetLoc sets the value of Loc.
func (s *ValidationError) SetLoc(val []ValidationErrorLocItem) {
	s.Loc = val
}

// SetMsg sets the value of Msg.
func (s *ValidationError) SetMsg(val string) {
	s.Msg = val
}

// SetType sets the value of Type.
func (s *ValidationError) SetType(val string) {
	s.Type = val
}

// ValidationErrorLocItem represents sum type.
type ValidationErrorLocItem struct {
	Type   ValidationErrorLocItemType // switch on this field
	String string
	Int    int
}

// ValidationErrorLocItemType is oneOf type of ValidationErrorLocItem.
type ValidationErrorLocItemType string

// Possible values for ValidationErrorLocItemType.
const (
	StringValidationErrorLocItem ValidationErrorLocItemType = "string"
	IntValidationErrorLocItem    ValidationErrorLocItemType = "int"
)

// IsString reports whether ValidationErrorLocItem is string.
func (s ValidationErrorLocItem) IsString() bool { return s.Type == StringValidationErrorLocItem }

// IsInt reports whether ValidationErrorLocItem is int.
func (s ValidationErrorLocItem) IsInt() bool { return s.Type == IntValidationErrorLocItem }

// SetString sets ValidationErrorLocItem to string.
func (s *ValidationErrorLocItem) SetString(v string) {
	s.Type = StringValidationErrorLocItem
	s.String = v
}

// GetString returns string and true boolean if ValidationErrorLocItem is string.
func (s ValidationErrorLocItem) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringValidationErrorLocItem returns new ValidationErrorLocItem from string.
func NewStringValidationErrorLocItem(v string) ValidationErrorLocItem {
	var s ValidationErrorLocItem
	s.SetString(v)
	return s
}

// SetInt sets ValidationErrorLocItem to int.
func (s *ValidationErrorLocItem) SetInt(v int) {
	s.Type = IntValidationErrorLocItem
	s.Int = v
}

// GetInt returns int and true boolean if ValidationErrorLocItem is int.
func (s ValidationErrorLocItem) GetInt() (v int, ok bool) {
	if !s.IsInt() {
		return v, false
	}
	return s.Int, true
}

// NewIntValidationErrorLocItem returns new ValidationErrorLocItem from int.
func NewIntValidationErrorLocItem(v int) ValidationErrorLocItem {
	var s ValidationErrorLocItem
	s.SetInt(v)
	return s
}
