# Coverage Pattern Configuration
# Defines which packages are unit-testable vs integration-testable for each service
#
# Unit-testable: Pure logic (config, validators, builders, formatters, metrics, classifiers)
# Integration-testable: I/O-dependent (handlers, servers, DB adapters, K8s clients, workers)

go_services:
  aianalysis:
    pkg_pattern: "/pkg/aianalysis/"
    # NOTE: File exclusions use .go: (colon after .go) because Go coverage format is file.go:line
    #       Directory exclusions use trailing / (e.g., audit/) to match subdirectory paths
    unit_exclude: "/(handler\\.go:|audit/)"
    integration_include: "/(handler\\.go:|audit/)"
  
  authwebhook:
    pkg_pattern: "/pkg/authwebhook/"
    # NOTE: All exclusions are file-level, so use .go: suffix (not .go/)
    #       notificationrequest_validator implements webhook.CustomValidator (needs K8s admission context)
    unit_exclude: "/(notificationrequest_handler|remediationapprovalrequest_handler|remediationrequest_handler|workflowexecution_handler|notificationrequest_validator)\\.go:"
    integration_include: "/(notificationrequest_handler|remediationapprovalrequest_handler|remediationrequest_handler|workflowexecution_handler|notificationrequest_validator)\\.go:"
  
  datastorage:
    pkg_pattern: "/pkg/datastorage/"
    # NOTE: adapter/, query/service.go, reconstruction/query.go use *sql.DB directly (integration-testable)
    #       File exclusions use .go: (Go coverage format), directory exclusions use /
    unit_exclude: "/(server/|repository/|dlq/|ogen-client/|mocks/|adapter/|query/service\\.go:|reconstruction/query\\.go:)"
    integration_include: "/(server/|repository/|dlq/|adapter/|query/service\\.go:|reconstruction/query\\.go:)"
  
  gateway:
    pkg_pattern: "/pkg/gateway/"
    # NOTE: server.go is a file (use .go:), k8s and processing/* are directories (use /)
    unit_exclude: "/(server\\.go:|k8s/|processing/(crd_creator|distributed_lock|status_updater)/)"
    integration_include: "/(server\\.go:|k8s/|processing/(crd_creator|distributed_lock|status_updater)/)"
  
  notification:
    pkg_pattern: "/pkg/notification/"
    # NOTE: client.go is a file (use .go:), delivery/phase/status are directories (use /)
    unit_exclude: "/(client\\.go:|delivery/|phase/|status/)"
    integration_include: "/(client\\.go:|delivery/|phase/|status/)"
  
  remediationorchestrator:
    pkg_pattern: "/pkg/remediationorchestrator/"
    unit_exclude: "/(creator|handler/(aianalysis|signalprocessing|workflowexecution)|aggregator|status)/"
    integration_include: "/(creator|handler/(aianalysis|signalprocessing|workflowexecution)|aggregator|status)/"
  
  signalprocessing:
    pkg_pattern: "/pkg/signalprocessing/"
    unit_exclude: "/(audit|cache|enricher|handler|status)/"
    integration_include: "/(audit|cache|enricher|handler|status)/"
  
  workflowexecution:
    pkg_pattern: "/pkg/workflowexecution/"
    unit_exclude: "/(audit|status)/"
    integration_include: "/(audit|status)/"

python_services:
  holmesgpt-api:
    unit_testable:
      - "models/"
      - "validation/"
      - "sanitization/"
      - "toolsets/"
      - "config/"
      - "audit/buffered_store.py"
      - "errors.py"
    integration_testable:
      - "extensions/"
      - "middleware/"
      - "auth/"
      - "clients/"
      - "main.py"
      - "audit/events.py"
      - "audit/factory.py"
      - "metrics/instrumentation.py"
