version: '3.8'

services:
  # Test runner - runs all tests
  test-runner:
    build:
      context: .
      dockerfile: docker/test-runner.Dockerfile
    volumes:
      - .:/workspace
      # Note: Podman socket mount removed - not needed for unit/integration tests
      # E2E tests that need Kind will run on host, not in container
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    environment:
      - GOFLAGS=-mod=mod
      - CGO_ENABLED=0
    networks:
      - test-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      datastorage:
        condition: service_healthy

  # PostgreSQL for integration tests
  # Using self-hosted multi-arch image to avoid Docker Hub rate limits
  postgres:
    image: quay.io/jordigilh/pgvector:pg16
    environment:
      POSTGRES_DB: action_history
      POSTGRES_USER: slm_user
      POSTGRES_PASSWORD: test_password
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slm_user -d action_history"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Redis for integration tests
  # Using self-hosted multi-arch image to avoid Docker Hub rate limits
  redis:
    image: quay.io/jordigilh/redis:7-alpine
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Data Storage Service for integration tests
  datastorage:
    build:
      context: .
      dockerfile: docker/data-storage.Dockerfile
    environment:
      - CONFIG_PATH=/etc/datastorage/config.yaml
    volumes:
      - ./test/integration/datastorage/config:/etc/datastorage:ro
    networks:
      - test-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # HolmesGPT-API Service for integration tests
  # AI analysis service with mock LLM for deterministic testing
  holmesgpt-api:
    build:
      context: .
      dockerfile: holmesgpt-api/Dockerfile
    environment:
      - CONFIG_PATH=/etc/holmesgpt/config.yaml
      # Mock LLM for integration tests (cost constraint)
      - LLM_PROVIDER=mock
      - MOCK_LLM_ENABLED=true
      # Data Storage connection
      - DATASTORAGE_URL=http://datastorage:8080
      # Logging
      - LOG_LEVEL=INFO
    ports:
      - "8081:8080"
    networks:
      - test-network
    depends_on:
      datastorage:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

volumes:
  go-mod-cache:
  go-build-cache:

networks:
  test-network:
    driver: bridge
