---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-controller
  namespace: kubernaut-notifications
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: notification-controller
    app.kubernetes.io/part-of: kubernaut
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notification-controller
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: notification-controller
    app.kubernetes.io/part-of: kubernaut
rules:
  # NotificationRequest CRD permissions
  - apiGroups:
      - notification.kubernaut.ai
    resources:
      - notificationrequests
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - notification.kubernaut.ai
    resources:
      - notificationrequests/status
    verbs:
      - get
      - update
      - patch
  # Secret permissions (for Slack webhook URL)
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  # Event permissions (for recording events)
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: notification-controller
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: notification-controller
    app.kubernetes.io/part-of: kubernaut
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: notification-controller
subjects:
  - kind: ServiceAccount
    name: notification-controller
    namespace: kubernaut-notifications


