//go:build !ignore_autogenerated

/*
Copyright 2025 Jordi Gil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSession) DeepCopyInto(out *AgentSession) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSession.
func (in *AgentSession) DeepCopy() *AgentSession {
	if in == nil {
		return nil
	}
	out := new(AgentSession)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSession) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionAlignmentFinding) DeepCopyInto(out *AgentSessionAlignmentFinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionAlignmentFinding.
func (in *AgentSessionAlignmentFinding) DeepCopy() *AgentSessionAlignmentFinding {
	if in == nil {
		return nil
	}
	out := new(AgentSessionAlignmentFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionAlignmentVerdict) DeepCopyInto(out *AgentSessionAlignmentVerdict) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]AgentSessionAlignmentFinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionAlignmentVerdict.
func (in *AgentSessionAlignmentVerdict) DeepCopy() *AgentSessionAlignmentVerdict {
	if in == nil {
		return nil
	}
	out := new(AgentSessionAlignmentVerdict)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionAlternativeWorkflow) DeepCopyInto(out *AgentSessionAlternativeWorkflow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionAlternativeWorkflow.
func (in *AgentSessionAlternativeWorkflow) DeepCopy() *AgentSessionAlternativeWorkflow {
	if in == nil {
		return nil
	}
	out := new(AgentSessionAlternativeWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionList) DeepCopyInto(out *AgentSessionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentSession, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionList.
func (in *AgentSessionList) DeepCopy() *AgentSessionList {
	if in == nil {
		return nil
	}
	out := new(AgentSessionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentSessionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionResult) DeepCopyInto(out *AgentSessionResult) {
	*out = *in
	if in.RootCauseAnalysis != nil {
		in, out := &in.RootCauseAnalysis, &out.RootCauseAnalysis
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectedWorkflow != nil {
		in, out := &in.SelectedWorkflow, &out.SelectedWorkflow
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.IsActionable != nil {
		in, out := &in.IsActionable, &out.IsActionable
		*out = new(bool)
		**out = **in
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AlternativeWorkflows != nil {
		in, out := &in.AlternativeWorkflows, &out.AlternativeWorkflows
		*out = make([]AgentSessionAlternativeWorkflow, len(*in))
		copy(*out, *in)
	}
	if in.ValidationAttemptsHistory != nil {
		in, out := &in.ValidationAttemptsHistory, &out.ValidationAttemptsHistory
		*out = make([]AgentSessionValidationAttempt, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DetectedLabels != nil {
		in, out := &in.DetectedLabels, &out.DetectedLabels
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.AlignmentVerdict != nil {
		in, out := &in.AlignmentVerdict, &out.AlignmentVerdict
		*out = new(AgentSessionAlignmentVerdict)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionResult.
func (in *AgentSessionResult) DeepCopy() *AgentSessionResult {
	if in == nil {
		return nil
	}
	out := new(AgentSessionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionSpec) DeepCopyInto(out *AgentSessionSpec) {
	*out = *in
	out.RemediationRequestRef = in.RemediationRequestRef
	if in.IsDuplicate != nil {
		in, out := &in.IsDuplicate, &out.IsDuplicate
		*out = new(bool)
		**out = **in
	}
	if in.OccurrenceCount != nil {
		in, out := &in.OccurrenceCount, &out.OccurrenceCount
		*out = new(int)
		**out = **in
	}
	if in.DeduplicationWindowMinutes != nil {
		in, out := &in.DeduplicationWindowMinutes, &out.DeduplicationWindowMinutes
		*out = new(int)
		**out = **in
	}
	if in.SignalLabels != nil {
		in, out := &in.SignalLabels, &out.SignalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SignalAnnotations != nil {
		in, out := &in.SignalAnnotations, &out.SignalAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.EnrichmentResults != nil {
		in, out := &in.EnrichmentResults, &out.EnrichmentResults
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionSpec.
func (in *AgentSessionSpec) DeepCopy() *AgentSessionSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSessionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionStatus) DeepCopyInto(out *AgentSessionStatus) {
	*out = *in
	if in.ActingUserGroups != nil {
		in, out := &in.ActingUserGroups, &out.ActingUserGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(AgentSessionResult)
		(*in).DeepCopyInto(*out)
	}
	if in.DispatchedAt != nil {
		in, out := &in.DispatchedAt, &out.DispatchedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionStatus.
func (in *AgentSessionStatus) DeepCopy() *AgentSessionStatus {
	if in == nil {
		return nil
	}
	out := new(AgentSessionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentSessionValidationAttempt) DeepCopyInto(out *AgentSessionValidationAttempt) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentSessionValidationAttempt.
func (in *AgentSessionValidationAttempt) DeepCopy() *AgentSessionValidationAttempt {
	if in == nil {
		return nil
	}
	out := new(AgentSessionValidationAttempt)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectRef) DeepCopyInto(out *ObjectRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectRef.
func (in *ObjectRef) DeepCopy() *ObjectRef {
	if in == nil {
		return nil
	}
	out := new(ObjectRef)
	in.DeepCopyInto(out)
	return out
}
