/*
Copyright 2025 Jordi Gil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package models

import (
	"encoding/json"
	"time"
)

// ========================================
// REMEDIATION WORKFLOW CATALOG MODELS
// ========================================
// Authority: DD-STORAGE-008 v2.0 (Workflow Catalog Schema)
// Business Requirement: BR-STORAGE-012 (Workflow Semantic Search)
// Design Decision: DD-NAMING-001 (Remediation Workflow Terminology)
// ========================================

// ExecutionEngine represents the workflow execution engine type
// Authority: ADR-043 (Workflow Execution Standards)
type ExecutionEngine string

const (
	// ExecutionEngineTekton represents Tekton Pipelines execution engine
	ExecutionEngineTekton ExecutionEngine = "tekton"
	// ExecutionEngineJob represents Kubernetes Job execution engine
	ExecutionEngineJob ExecutionEngine = "job"
)

// RemediationWorkflow represents a workflow in the catalog
// Maps to remediation_workflow_catalog table (migration 015)
type RemediationWorkflow struct {
	// ========================================
	// IDENTITY (DD-WORKFLOW-002 v3.0, DD-WORKFLOW-012 v2.0)
	// ========================================
	// WorkflowID is UUID primary key (auto-generated by database)
	WorkflowID string `json:"workflow_id" db:"workflow_id"`
	// WorkflowName is the human-readable identifier (e.g., "pod-oom-recovery")
	WorkflowName string `json:"workflow_name" db:"workflow_name" validate:"required,max=255"`
	// Version is semantic version (e.g., "v1.0.0")
	Version string `json:"version" db:"version" validate:"required,max=50"`

	// ========================================
	// METADATA
	// ========================================
	Name string `json:"name" db:"name" validate:"required,max=255"`
	// Description is a structured JSONB description (BR-WORKFLOW-004, migration 026)
	// Format: {"what": "...", "whenToUse": "...", "whenNotToUse": "...", "preconditions": "..."}
	Description StructuredDescription `json:"description" db:"description" validate:"required"`
	Owner       *string `json:"owner,omitempty" db:"owner" validate:"omitempty,max=255"`
	Maintainer  *string `json:"maintainer,omitempty" db:"maintainer" validate:"omitempty,max=255,email"`

	// ========================================
	// CONTENT
	// ========================================
	Content     string `json:"content" db:"content" validate:"required"`
	ContentHash string `json:"content_hash" db:"content_hash" validate:"required,len=64"`

	// ========================================
	// ACTION TYPE (DD-WORKFLOW-016, DD-HAPI-017)
	// ========================================
	// ActionType links to action_type_taxonomy table (migration 025)
	// Required for three-step discovery protocol (list actions -> list workflows -> get workflow)
	ActionType string `json:"action_type" db:"action_type" validate:"required"`

	// ========================================
	// EXECUTION (ADR-043, DD-WORKFLOW-002 v2.4)
	// ========================================
	// Parameters is nullable JSONB - use pointer to handle NULL values from database
	Parameters      *json.RawMessage `json:"parameters,omitempty" db:"parameters"`
	ExecutionEngine ExecutionEngine  `json:"execution_engine" db:"execution_engine"`
	ContainerImage  *string          `json:"container_image,omitempty" db:"container_image"`
	ContainerDigest *string          `json:"container_digest,omitempty" db:"container_digest"`

	// ========================================
	// LABELS (V1.0: STRUCTURED TYPES FOR TYPE SAFETY)
	// ========================================
	// DD-CONTEXT-005: Filter Before LLM pattern
	// DD-WORKFLOW-001 v2.3: Structured label types for zero unstructured data
	// V1.0: Replaced json.RawMessage with structured types for compile-time validation

	// Labels contains the 5 mandatory workflow labels
	// Required: YES (signalType, severity, component, environment, priority)
	// Authority: DD-WORKFLOW-001 v1.4
	Labels MandatoryLabels `json:"labels" db:"labels" validate:"required"`

	// CustomLabels contains customer-defined labels for hard filtering
	// DD-WORKFLOW-001 v1.5: Subdomain-based extraction design
	// Format: map[subdomain][]string
	// Example: {"constraint": ["cost-constrained"], "team": ["name=payments"]}
	// V1.0: Structured map for type safety
	CustomLabels CustomLabels `json:"custom_labels,omitempty" db:"custom_labels"`

	// DetectedLabels contains auto-detected labels from Kubernetes resources
	// DD-WORKFLOW-001 v2.2: 8 auto-detected fields with wildcard support
	// V1.0: Structured type for compile-time validation
	// Note: Not a pointer - FailedDetections field tracks detection failures
	DetectedLabels DetectedLabels `json:"detected_labels,omitempty" db:"detected_labels"`

	// ========================================
	// EMBEDDING COLUMN (DEPRECATED - NOT USED FOR SEARCH)
	// ========================================
	// V1.0: Embedding column removed from workflow search
	// Authority: CONFIDENCE_ASSESSMENT_REMOVE_EMBEDDINGS.md (92% confidence)
	// Rationale: Indeterministic LLM keywords decrease correctness
	// Future: May store embeddings for manual description search, but NOT for workflow selection
	// For now: Column exists in DB but is not populated or queried

	// ========================================
	// LIFECYCLE MANAGEMENT
	// ========================================
	Status         string     `json:"status" db:"status" validate:"required,oneof=active disabled deprecated archived"`
	StatusReason   *string    `json:"status_reason,omitempty" db:"status_reason"` // Migration 022: Reason for status change
	DisabledAt     *time.Time `json:"disabled_at,omitempty" db:"disabled_at"`
	DisabledBy     *string    `json:"disabled_by,omitempty" db:"disabled_by" validate:"omitempty,max=255"`
	DisabledReason *string    `json:"disabled_reason,omitempty" db:"disabled_reason"`

	// ========================================
	// VERSION MANAGEMENT
	// ========================================
	IsLatestVersion   bool    `json:"is_latest_version" db:"is_latest_version"`
	PreviousVersion   *string `json:"previous_version,omitempty" db:"previous_version" validate:"omitempty,max=50"`
	DeprecationNotice *string `json:"deprecation_notice,omitempty" db:"deprecation_notice"`

	// ========================================
	// VERSION CHANGE METADATA
	// ========================================
	VersionNotes  *string    `json:"version_notes,omitempty" db:"version_notes"`
	ChangeSummary *string    `json:"change_summary,omitempty" db:"change_summary"`
	ApprovedBy    *string    `json:"approved_by,omitempty" db:"approved_by" validate:"omitempty,max=255"`
	ApprovedAt    *time.Time `json:"approved_at,omitempty" db:"approved_at"`

	// ========================================
	// SUCCESS METRICS (ADR-033)
	// ========================================
	ExpectedSuccessRate     *float64 `json:"expected_success_rate,omitempty" db:"expected_success_rate" validate:"omitempty,min=0,max=1"`
	ExpectedDurationSeconds *int     `json:"expected_duration_seconds,omitempty" db:"expected_duration_seconds" validate:"omitempty,min=0"`
	ActualSuccessRate       *float64 `json:"actual_success_rate,omitempty" db:"actual_success_rate" validate:"omitempty,min=0,max=1"`
	TotalExecutions         int      `json:"total_executions" db:"total_executions" validate:"min=0"`
	SuccessfulExecutions    int      `json:"successful_executions" db:"successful_executions" validate:"min=0"`

	// ========================================
	// AUDIT TRAIL
	// ========================================
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	CreatedBy *string   `json:"created_by,omitempty" db:"created_by" validate:"omitempty,max=255"`
	UpdatedBy *string   `json:"updated_by,omitempty" db:"updated_by" validate:"omitempty,max=255"`
}

// ========================================
// WORKFLOW SEARCH REQUEST
// ========================================
// Business Requirement: BR-STORAGE-013 (Label-Based Workflow Search)
// Design Decision: DD-WORKFLOW-004 (Hybrid Weighted Label Scoring - V1.5 Label-Only)
// Authority: CONFIDENCE_ASSESSMENT_REMOVE_EMBEDDINGS.md (92% confidence - embeddings removed)

// WorkflowSearchRequest represents a label-only workflow search request
// V1.0: Pure label matching with wildcard weighting (no embeddings)
// Rationale: Indeterministic LLM-generated keywords decrease correctness (81% → 95%)
type WorkflowSearchRequest struct {
	// RemediationID is the parent remediation request ID for audit correlation
	// BR-AUDIT-023: Used as correlation_id in audit events
	RemediationID string `json:"remediation_id,omitempty"`

	// Filters for label-based matching (REQUIRED)
	// Must include at minimum: signalType, severity, component, environment, priority
	// Authority: DD-CONTEXT-005 (Filter Before LLM pattern)
	Filters *WorkflowSearchFilters `json:"filters" validate:"required"`

	// TopK is the number of results to return (default: 10, max: 100)
	TopK int `json:"top_k,omitempty" validate:"omitempty,min=1,max=100"`

	// MinScore is the minimum normalized score threshold (0.0-1.0)
	// Default: 0.0 (no threshold)
	// Workflows with score < MinScore are excluded from results
	MinScore float64 `json:"min_score,omitempty" validate:"omitempty,min=0,max=1"`

	// IncludeDisabled includes disabled workflows in results (default: false)
	IncludeDisabled bool `json:"include_disabled,omitempty"`
}

// WorkflowSearchFilters represents label-based filters
// DD-CONTEXT-005: Filter Before LLM pattern
// DD-LLM-001: MCP Workflow Search Parameter Taxonomy
// DD-WORKFLOW-004: Hybrid Weighted Label Scoring
// DD-WORKFLOW-001 v1.6: All API fields use snake_case
type WorkflowSearchFilters struct {
	// ========================================
	// MANDATORY LABELS (Strict Filtering) - 5 per DD-WORKFLOW-001 v1.4
	// ========================================
	// Authority: DD-WORKFLOW-001 v1.6 (Mandatory Workflow Label Schema)

	// SignalType filters by single alert/signal type (MANDATORY)
	// Example: "OOMKilled", "MemoryLeak", "DatabaseConnectionLeak"
	// DD-WORKFLOW-001 v1.6: snake_case JSON tag
	SignalType string `json:"signal_type" validate:"required"`

	// Severity filters by severity level (MANDATORY)
	// Values: "critical", "high", "medium", "low"
	// DD-WORKFLOW-001 v1.6: snake_case JSON tag
	Severity string `json:"severity" validate:"required,oneof=critical high medium low"`

	// Component filters by Kubernetes resource type (MANDATORY)
	// Example: "pod", "deployment", "node", "service"
	// DD-WORKFLOW-001 v1.4: Added as mandatory label
	Component string `json:"component" validate:"required"`

	// Environment filters by deployment environment (MANDATORY)
	// Source: Single value from Signal Processing
	// DD-WORKFLOW-001 v2.5: Single string (searches workflows with array containing this value)
	Environment string `json:"environment" validate:"required"`

	// Priority filters by priority level (MANDATORY)
	// Values: "P0", "P1", "P2", "P3"
	// DD-WORKFLOW-001 v1.4: Moved from optional to mandatory
	Priority string `json:"priority" validate:"required,oneof=P0 P1 P2 P3"`

	// ========================================
	// DETECTED LABELS (Auto-detected from K8s)
	// ========================================
	// Authority: DD-WORKFLOW-001 v1.6 (DetectedLabels section)

	// DetectedLabels contains auto-detected labels from Kubernetes resources
	// DD-WORKFLOW-001 v2.2: 8 auto-detected fields with wildcard support
	// V1.0: Not a pointer - FailedDetections field tracks detection failures
	DetectedLabels DetectedLabels `json:"detected_labels,omitempty"`

	// ========================================
	// CUSTOM LABELS (Customer-defined)
	// ========================================
	// Authority: DD-WORKFLOW-001 v1.5 (Custom Labels section)

	// CustomLabels contains customer-defined labels for hard filtering
	// DD-WORKFLOW-001 v1.5: Subdomain-based extraction design
	// Format: map[subdomain][]string
	// Example: {"constraint": ["cost-constrained"], "team": ["name=payments"]}
	CustomLabels map[string][]string `json:"custom_labels,omitempty"`

	// ========================================
	// METADATA FILTERS
	// ========================================

	// WorkflowName filters by exact workflow name match (metadata field)
	// Used for test idempotency and workflow lookup by human-readable name
	// Authority: DD-API-001 (OpenAPI client mandatory - added in Jan 2026)
	// Example: "oomkill-increase-memory-v1"
	WorkflowName string `json:"workflow_name,omitempty"`

	// ========================================
	// LIFECYCLE FILTERS
	// ========================================

	// Status filters by workflow lifecycle status
	// Default: ["active"] if not specified
	Status []string `json:"status,omitempty"`
}

// V1.0: DetectedLabels type moved to workflow_labels.go
// Authority: DD-WORKFLOW-001 v2.3 - Structured types for zero unstructured data
// See: pkg/datastorage/models/workflow_labels.go for MandatoryLabels, CustomLabels, DetectedLabels

// ShouldSkipDetectedLabel returns true if the given field name should be skipped
// because it's in the failedDetections list.
// DD-WORKFLOW-001 v2.1: When matching incident DetectedLabels against workflow
// catalog detected_labels, skip fields that are in failedDetections.
func ShouldSkipDetectedLabel(fieldName string, failedDetections []string) bool {
	if len(failedDetections) == 0 {
		return false
	}
	for _, failed := range failedDetections {
		if failed == fieldName {
			return true
		}
	}
	return false
}

// IsValidFailedDetectionField returns true if the given field name is a valid
// DetectedLabels field that can be included in failedDetections.
// DD-WORKFLOW-001 v2.1: Validation for failedDetections field names
// V1.0: Uses ValidDetectedLabelFields from workflow_labels.go
func IsValidFailedDetectionField(fieldName string) bool {
	for _, valid := range ValidDetectedLabelFields {
		if valid == fieldName {
			return true
		}
	}
	return false
}

// ========================================
// WORKFLOW SEARCH RESPONSE
// ========================================

// WorkflowSearchResponse represents label-only search results
// V1.0: No query field (label-only search)
type WorkflowSearchResponse struct {
	// Workflows is the list of matching workflows, ranked by label score
	Workflows []WorkflowSearchResult `json:"workflows"`

	// TotalResults is the total number of matching workflows
	TotalResults int `json:"total_results"`

	// Filters are the applied filters (now required for all searches)
	Filters *WorkflowSearchFilters `json:"filters"`
}

// WorkflowSearchResult represents a single search result with label-based scoring
// DD-WORKFLOW-002 v3.0: FLAT response structure (no nested workflow object)
// DD-WORKFLOW-004 v1.5: Label-Only Scoring with Wildcard Weighting
// Authority: CONFIDENCE_ASSESSMENT_REMOVE_EMBEDDINGS.md (92% confidence)
type WorkflowSearchResult struct {
	// ========================================
	// DD-WORKFLOW-002 v3.0: FLAT RESPONSE STRUCTURE
	// ========================================
	// Workflow fields are embedded directly (not nested) per DD-WORKFLOW-002 v3.0
	// This provides a flat JSON structure: {"workflow_id": "...", "title": "...", "confidence": 0.95}

	// WorkflowID is the UUID primary key (DD-WORKFLOW-002 v3.0)
	WorkflowID string `json:"workflow_id"`

	// Title is the human-readable workflow name (DD-WORKFLOW-002 v3.0: renamed from "name")
	Title string `json:"title"`

	// Description is the structured workflow description (BR-WORKFLOW-004)
	Description StructuredDescription `json:"description"`

	// SignalType is the signal type this workflow handles (DD-WORKFLOW-002 v3.0: singular, not array)
	SignalType string `json:"signal_type"`

	// ContainerImage is the OCI bundle reference (DD-CONTRACT-001 v1.2)
	ContainerImage string `json:"container_image,omitempty"`

	// ContainerDigest is the sha256 digest for audit (DD-CONTRACT-001 v1.2)
	ContainerDigest string `json:"container_digest,omitempty"`

	// ========================================
	// V1.0: LABEL-ONLY SCORING COMPONENTS
	// ========================================
	// Authority: DD-WORKFLOW-004 v1.5 (Label-Only Scoring with Wildcard Weighting)
	// Rationale: Pure label matching increases correctness 81% → 95%

	// Confidence is the normalized label score (0.0-1.0) - DD-WORKFLOW-002 v3.0 name
	// Formula: (mandatory_match_score + label_boost - label_penalty) / 10.0
	// Range: 0.0-1.0 (normalized from raw score range 0.0-10.0)
	Confidence float64 `json:"confidence" validate:"min=0,max=1"`

	// LabelBoost is the boost from matching DetectedLabels (0.0-0.39)
	// Sum of all matching DetectedLabel weights (with wildcard weighting)
	// Max: 0.10 (gitOpsManaged) + 0.10 (gitOpsTool) + 0.05 (pdbProtected) + ... = 0.39
	// Wildcard matches get 50% of boost (e.g., gitOpsTool='*' → 0.05 instead of 0.10)
	LabelBoost float64 `json:"label_boost" validate:"min=0,max=0.39"`

	// LabelPenalty is the penalty from conflicting DetectedLabels (0.0-0.20)
	// Sum of all conflicting high-impact DetectedLabel weights
	// High-impact conflicts: gitOpsManaged, pdbProtected
	LabelPenalty float64 `json:"label_penalty" validate:"min=0,max=0.20"`

	// FinalScore is the normalized label score (0.0-1.0)
	// Same as Confidence (provided for consistency with DD-WORKFLOW-004)
	FinalScore float64 `json:"final_score" validate:"min=0,max=1"`

	// Rank is the position in the result set (1-based)
	Rank int `json:"rank" validate:"min=1"`

	// ========================================
	// DD-WORKFLOW-001 v1.6: LABEL COLUMNS IN RESPONSE
	// ========================================

	// CustomLabels contains customer-defined labels for hard filtering
	// DD-WORKFLOW-001 v1.5: Subdomain-based extraction design
	// Format: map[subdomain][]string
	// Example: {"constraint": ["cost-constrained"], "team": ["name=payments"]}
	// V1.0: Structured type for compile-time validation
	CustomLabels CustomLabels `json:"custom_labels,omitempty"`

	// DetectedLabels contains auto-detected labels from Kubernetes resources
	// DD-WORKFLOW-001 v2.2: 8 auto-detected fields with wildcard support
	// V1.0: Structured type for compile-time validation
	// Note: Not a pointer - FailedDetections field tracks detection failures
	DetectedLabels DetectedLabels `json:"detected_labels,omitempty"`

	// ========================================
	// PARAMETER SCHEMA (BR-HAPI-191)
	// ========================================
	// Parameters contains the workflow parameter schema (JSONB)
	// Used by HAPI for parameter validation and by LLM for correct parameter names
	// Format: {"schema": {"parameters": [{"name": "PARAM_NAME", "type": "string", ...}]}}
	Parameters *json.RawMessage `json:"parameters,omitempty"`

	// ========================================
	// INTERNAL: Full workflow data (not serialized to JSON)
	// ========================================
	// Workflow contains the full workflow data for internal processing
	// This is not included in the JSON response per DD-WORKFLOW-002 v3.0
	Workflow RemediationWorkflow `json:"-"`
}

// ========================================
// HELPER METHODS
// ========================================

// IsActive returns true if the workflow is active
func (w *RemediationWorkflow) IsActive() bool {
	return w.Status == "active"
}

// IsDisabled returns true if the workflow is disabled
func (w *RemediationWorkflow) IsDisabled() bool {
	return w.Status == "disabled"
}

// IsDeprecated returns true if the workflow is deprecated
func (w *RemediationWorkflow) IsDeprecated() bool {
	return w.Status == "deprecated"
}

// IsArchived returns true if the workflow is archived
func (w *RemediationWorkflow) IsArchived() bool {
	return w.Status == "archived"
}

// V1.0: Removed GetLabelsMap() and SetLabelsFromMap() methods
// Rationale: With structured types, direct field access is preferred
// Migration: Use w.Labels.SignalType instead of map["signalType"]
// Authority: Zero unstructured data mandate for V1.0

// ========================================
// WORKFLOW LIST RESPONSE
// ========================================

// WorkflowListResponse represents paginated workflow list results
type WorkflowListResponse struct {
	Workflows []*RemediationWorkflow `json:"workflows"`
	Limit     int                    `json:"limit"`
	Offset    int                    `json:"offset"`
	Total     int                    `json:"total"`
}

// WorkflowVersionsResponse represents all versions of a workflow by workflow_name
// DD-WORKFLOW-002 v3.0: List all versions by workflow_name
type WorkflowVersionsResponse struct {
	WorkflowName string                `json:"workflow_name"`
	Versions     []RemediationWorkflow `json:"versions"`
	Total        int                   `json:"total"`
}

// WorkflowUpdateRequest represents a request to update mutable workflow fields
// DD-WORKFLOW-012: Only mutable fields can be updated (status, metrics)
// Immutable fields (description, content, labels) require creating a new version
type WorkflowUpdateRequest struct {
	// Mutable fields (DD-WORKFLOW-012)
	Status         *string `json:"status,omitempty"`          // active, disabled, deprecated, archived
	DisabledBy     *string `json:"disabled_by,omitempty"`     // Who disabled the workflow
	DisabledReason *string `json:"disabled_reason,omitempty"` // Why the workflow was disabled

	// Immutable fields - included for validation (will be rejected if provided)
	Description *StructuredDescription `json:"description,omitempty"` // IMMUTABLE - rejected if provided
	Content     *string          `json:"content,omitempty"`     // IMMUTABLE - rejected if provided
	Labels      *json.RawMessage `json:"labels,omitempty"`      // IMMUTABLE - rejected if provided
}

// WorkflowDisableRequest represents a request to disable a workflow
// DD-WORKFLOW-012: Convenience endpoint for soft-delete (status = disabled)
type WorkflowDisableRequest struct {
	Reason    *string `json:"reason,omitempty"`     // Why the workflow is being disabled
	UpdatedBy *string `json:"updated_by,omitempty"` // Who is disabling the workflow
}
