// Code generated by ogen, DO NOT EDIT.

package client

import (
	"context"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetConfigConfigGet implements get_config_config_get operation.
//
// Get service configuration (sanitized)
// Business Requirement: BR-HAPI-128 (Configuration endpoint).
//
// GET /config
func (UnimplementedHandler) GetConfigConfigGet(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// HealthCheckHealthGet implements health_check_health_get operation.
//
// Liveness probe endpoint
// Business Requirement: BR-HAPI-126 (Health check endpoint).
//
// GET /health
func (UnimplementedHandler) HealthCheckHealthGet(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// IncidentAnalyzeEndpointAPIV1IncidentAnalyzePost implements incident_analyze_endpoint_api_v1_incident_analyze_post operation.
//
// Analyze initial incident and provide RCA + workflow selection
// Business Requirement: BR-HAPI-002 (Incident analysis endpoint)
// Business Requirement: BR-WORKFLOW-001 (MCP Workflow Integration)
// Business Requirement: BR-AUDIT-005 v2.0 (Gap #4 - AI Provider Data)
// Design Decision: DD-AUDIT-005 (Hybrid Provider Data Capture)
// Design Decision: DD-AUTH-006 (User attribution for LLM cost tracking)
// Called by: AIAnalysis Controller (for initial incident RCA and workflow selection)
// Flow:
// 1. Receive IncidentRequest from AIAnalysis
// 2. Extract authenticated user from oauth-proxy header (DD-AUTH-006)
// 3. Sanitize input for LLM (BR-HAPI-211)
// 4. Call HolmesGPT SDK for investigation (BR-HAPI-002)
// 5. Search workflow catalog via MCP (BR-HAPI-250)
// 6. Validate workflow response (DD-HAPI-002 v1.2)
// 7. Self-correct if validation fails (up to 3 attempts)
// 8. Emit audit event with complete response (DD-AUDIT-005)
// 9. Return IncidentResponse with RCA and workflow selection.
//
// POST /api/v1/incident/analyze
func (UnimplementedHandler) IncidentAnalyzeEndpointAPIV1IncidentAnalyzePost(ctx context.Context, req *IncidentRequest) (r IncidentAnalyzeEndpointAPIV1IncidentAnalyzePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadinessCheckReadyGet implements readiness_check_ready_get operation.
//
// Readiness probe endpoint
// Business Requirements:
// - BR-HAPI-127 (Readiness check endpoint)
// - BR-HAPI-201 (Graceful shutdown with DD-007 pattern)
// TDD GREEN Phase: Check shutdown flag first
// REFACTOR phase: Real dependency health checks.
//
// GET /ready
func (UnimplementedHandler) ReadinessCheckReadyGet(ctx context.Context) (r jx.Raw, _ error) {
	return r, ht.ErrNotImplemented
}

// RecoveryAnalyzeEndpointAPIV1RecoveryAnalyzePost implements recovery_analyze_endpoint_api_v1_recovery_analyze_post operation.
//
// Analyze failed action and provide recovery strategies
// Business Requirement: BR-HAPI-001 (Recovery analysis endpoint)
// Design Decision: DD-WORKFLOW-002 v2.4 - WorkflowCatalogToolset via SDK
// Design Decision: DD-AUTH-006 (User attribution for LLM cost tracking)
// Called by: AIAnalysis Controller (for recovery attempts after workflow failure).
//
// POST /api/v1/recovery/analyze
func (UnimplementedHandler) RecoveryAnalyzeEndpointAPIV1RecoveryAnalyzePost(ctx context.Context, req *RecoveryRequest) (r RecoveryAnalyzeEndpointAPIV1RecoveryAnalyzePostRes, _ error) {
	return r, ht.ErrNotImplemented
}
