{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.workflowexecution.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubernaut.fullname" . }}-workflowexecution
  namespace: {{ .Release.Namespace }}
  labels:
    app: workflowexecution-controller
    {{- include "kubernaut.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: workflowexecution-controller
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- include "kubernaut.np.metricsIngress" $ | nindent 4 }}
  egress:
    {{- include "kubernaut.np.commonEgress" . | nindent 4 }}
    {{- include "kubernaut.np.datastorageEgress" . | nindent 4 }}
{{- end }}
