version: 2

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - govet
    - ineffassign
    - misspell

run:
  timeout: 10m
  tests: true

issues:
  exclude-use-default: false
  max-same-issues: 100
