apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-storage-role
  namespace: kubernaut
rules:
  # Allow reading ConfigMaps for configuration
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Allow reading Secrets for database credentials
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

