apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-storage-rolebinding
  namespace: kubernaut-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-storage-role
subjects:
  - kind: ServiceAccount
    name: data-storage-sa
    namespace: kubernaut-system

