apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-storage-metrics
  namespace: kubernaut
  labels:
    app: data-storage-service
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: data-storage-service
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scheme: http

