# This rule is not used by the project kubernaut itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kubernetesexecution.kubernaut.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/managed-by: kustomize
  name: kubernetesexecution-kubernetesexecution-viewer-role
rules:
- apiGroups:
  - kubernetesexecution.kubernaut.io
  resources:
  - kubernetesexecutions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubernetesexecution.kubernaut.io
  resources:
  - kubernetesexecutions/status
  verbs:
  - get
