# This rule is not used by the project kubernaut itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over workflowexecution.kubernaut.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/managed-by: kustomize
  name: workflowexecution-workflowexecution-admin-role
rules:
- apiGroups:
  - workflowexecution.kubernaut.io
  resources:
  - workflowexecutions
  verbs:
  - '*'
- apiGroups:
  - workflowexecution.kubernaut.io
  resources:
  - workflowexecutions/status
  verbs:
  - get
