apiVersion: v1
kind: Service
metadata:
  name: alertmanager-service
  namespace: kubernaut-integration
  labels:
    app: alertmanager
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: alertmanager
  selector:
    app: alertmanager
---
# NodePort service for external access during development
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-nodeport
  namespace: kubernaut-integration
  labels:
    app: alertmanager
    component: monitoring
    service-type: external-access
spec:
  type: NodePort
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 30093
    protocol: TCP
    name: alertmanager
  selector:
    app: alertmanager
