---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: kubernaut-gateway
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: kubernaut
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: gateway

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-metrics
  namespace: kubernaut-gateway
  labels:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: kubernaut
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: kubernaut
    app.kubernetes.io/component: gateway

