/*
Copyright 2025 Jordi Gil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package infrastructure

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	sharedtypes "github.com/jordigilh/kubernaut/pkg/shared/types"
)

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Fleet Demo — Helm Chart Install (Issue #2337)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//
// hack/setup-fleet-infra's counterpart to InstallFullPipelineHelmChart
// (fullpipeline_e2e_helm.go): same exec.Command("helm", ...) pattern, but for
// the demo/QE entry point rather than the E2E Ginkgo suite -- no mock-LLM, no
// DEX test double, no locally-built/retagged images (this installs against
// the chart's own default public images, same as a real user would).
//
// Default experience is Console-first (BR-PLATFORM-014): Gateway starts
// disabled so a new user investigates/remediates the first demo scenario via
// Console chat before opting into the fully autonomous, Gateway-driven flow
// with -autonomous=true.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

const (
	// fleetDemoTraefikNamespace matches deployTraefikForKind's hardcoded
	// "traefik-system" (fleet_e2e.go) -- Console's NetworkPolicy needs this
	// namespace on its ingress allowlist since Traefik forwards browser
	// traffic into kubernaut-system cross-namespace.
	fleetDemoTraefikNamespace = "traefik-system"
	// fleetDemoKeycloakRealm matches keycloak-realm-fleet.json's "kubernaut-fleet"
	// realm name.
	fleetDemoKeycloakRealm = "kubernaut-fleet"
	// fleetDemoConsoleHost/Port match the "kubernaut-console.local:8843"
	// hostname+hostPort combination deployTraefikForKind/kind-fullpipeline-config.yaml
	// already wire up (traefikWebsecureNodePort 30843 -> host 8843).
	fleetDemoConsoleHost = "kubernaut-console.local"
	fleetDemoConsolePort = 8843
	// fleetDemoConsoleClientID/Secret match the "kubernaut-console" OIDC
	// client already registered in keycloak-realm-fleet.json -- not a new
	// credential, reusing that existing test-realm artifact.
	fleetDemoConsoleClientID     = "kubernaut-console"
	fleetDemoConsoleClientSecret = "e2e-console-secret"

	fleetDemoConsoleOAuthSecretName = "console-oauth-creds"
	// fleetDemoLLMSecretName is a fixed convention, NOT generated by this
	// tool: the user creates this Secret themselves before running
	// hack/setup-fleet-infra (README "Try It Out" step 1), mirroring
	// charts/kubernaut/README.md's own Quick Start.
	fleetDemoLLMSecretName    = "llm-credentials-primary"
	fleetDemoPGSecretName     = "postgresql-secret"
	fleetDemoValkeySecretName = "valkey-secret"
)

// fleetDemoDefaultSPPolicyRego is the baked-in SignalProcessing default
// (Issue #2337): a genuine catch-all -- classifies environment/severity/
// priority for ANY input via safe defaults (unknown/P3) rather than
// rejecting unrecognized signals, same generic BR-SP-051/070/105 logic fleet
// E2E already exercises via fullPipelineSignalProcessingPolicyRego. Reused
// directly (not copied) since it's genuinely generic, not E2E-specific.
const fleetDemoDefaultSPPolicyRego = fullPipelineSignalProcessingPolicyRego

// fleetDemoDefaultAAPolicyRego is the baked-in AIAnalysis default (Issue
// #2337): unconditionally requires human approval for every workflow,
// regardless of environment/severity -- deliberately its OWN policy, not
// fullPipelineAIAnalysisPolicyRego (which auto-approves outside production).
// A demo should never auto-execute a remediation action without an explicit
// "go ahead" from whoever's driving Console -- override via -aa-policy-file
// once you have your own approval policy.
const fleetDemoDefaultAAPolicyRego = `package aianalysis.approval
import rego.v1

default require_approval := true

reason := "Kubernaut demo default policy: every workflow requires human approval (override with -aa-policy-file)"
`

// FleetDemoHelmOptions configures InstallFleetDemoHelmChart's `helm install`
// invocation. Options-pattern struct (AGENTS.md 8-parameter limit) rather
// than growing InstallFleetDemoHelmChart's own parameter list.
//
// Deliberately does NOT include an LLM API key/file field: the LLM Secret
// (fleetDemoLLMSecretName) is the one thing a first-time user must create
// themselves (`kubectl create secret generic llm-credentials-primary
// --from-literal=api_key=... -n kubernaut-system`, mirroring charts/kubernaut/
// README.md's own Quick Start) -- this tool never reads or handles that
// credential material, and the chart's own pre-install validation (see that
// Quick Start) already fails with an actionable error if it's missing.
type FleetDemoHelmOptions struct {
	// Autonomous, when true, sets gateway.enabled=true so AlertManager-sourced
	// signals auto-create RemediationRequests. false (the default) leaves
	// Gateway disabled -- Prometheus/AlertManager still fire real alerts, but
	// nothing auto-remediates until the user asks Console to investigate, so
	// a new user experiences the remediation flow deliberately before opting
	// into the fully autonomous one.
	Autonomous bool
	// LLMProvider/LLMModel/LLMEndpoint configure global.llmProfiles.primary.*
	// -- required, no hardcoded default (varies per user's own LLM provider,
	// same reason the split-infra design never baked these into shared
	// test-infra Go code). Not sensitive -- these are plain Helm values, not
	// Secret material.
	LLMProvider string
	LLMModel    string
	LLMEndpoint string
	// SPPolicyFile/AAPolicyFile override the baked-in demo Rego policies
	// (fleetDemoDefaultSPPolicyRego/fleetDemoDefaultAAPolicyRego -- a
	// catch-all classification policy and an unconditional
	// "always require approval" gate, respectively) with a user-supplied
	// file. Empty uses the baked-in defaults; neither policy ships in the
	// chart itself (charts/kubernaut/README.md's Quick Start: "the chart
	// does not bundle default Rego policies").
	SPPolicyFile string
	AAPolicyFile string
	// ImageTag optionally overrides the container image tag for the fleet
	// demo chart (global.image.tag). When empty (the default), no --set is
	// emitted and the chart's kubernaut.image helper falls back to
	// .Chart.AppVersion (global.image.tag defaults to "").
	ImageTag string
	// VertexProject/VertexLocation feed global.llmProfiles.primary.vertexProject
	// / vertexLocation -- required by the chart when LLMProvider is vertex_ai
	// (the provider hosts Claude/Gemini models and derives its endpoint from
	// project/location). Empty for every other provider; no --set is emitted
	// then, keeping non-Vertex renders unchanged.
	VertexProject  string
	VertexLocation string
}

// Validate reports every missing required flag in one error, so
// hack/setup-fleet-infra's caller can tell the user everything they need to
// fix in a single run instead of one flag at a time.
func (o FleetDemoHelmOptions) Validate() error {
	var missing []string
	if o.LLMProvider == "" {
		missing = append(missing, "-llm-provider")
	}
	if o.LLMModel == "" {
		missing = append(missing, "-llm-model")
	}
	// Endpoint is required for every provider except vertex_ai, whose
	// endpoint is derived from project/location by the SDK (issue #2355) --
	// mirrors the platform contract in pkg/shared/types LLMConfig
	// validateProviderRequiredFields (endpoint required only for
	// openai/openai_compatible).
	if o.LLMEndpoint == "" && o.LLMProvider != sharedtypes.LLMProviderVertexAI {
		missing = append(missing, "-llm-endpoint")
	}
	if o.LLMProvider == sharedtypes.LLMProviderVertexAI {
		if o.VertexProject == "" {
			missing = append(missing, "-vertex-project")
		}
		if o.VertexLocation == "" {
			missing = append(missing, "-vertex-location")
		}
	}
	if len(missing) > 0 {
		return fmt.Errorf("missing required flags: %s", strings.Join(missing, ", "))
	}
	return nil
}

// buildFleetDemoHelmArgs builds the `helm upgrade --install` argument list
// for the fleet demo entry point. Pure function (no exec/cluster access) so
// it's unit-testable independent of InstallFleetDemoHelmChart's I/O.
//
// Deliberately no --wait: same reason as InstallFullPipelineHelmChart --
// charts/kubernaut/templates/hooks/migration-job.yaml is a post-install hook,
// and DataStorage's Deployment can never become ready before it runs, which
// deadlocks --wait until timeout.
func buildFleetDemoHelmArgs(kubeconfigPath, chartPath, namespace string, fleetOpts *FleetHelmOptions, opts FleetDemoHelmOptions, spPolicyFile, aaPolicyFile string) []string {
	keycloakAuthBase := fmt.Sprintf("https://keycloak:8443/realms/%s", fleetDemoKeycloakRealm)
	keycloakInClusterBase := fmt.Sprintf("https://keycloak.%s.svc.cluster.local:8443/realms/%s", idpNamespace, fleetDemoKeycloakRealm)

	args := []string{
		"--kubeconfig", kubeconfigPath,
		"upgrade", "--install", "kubernaut", chartPath,
		"--namespace", namespace,
		"--create-namespace",
		"--timeout", "8m",
		"--set", "global.llmProfiles.primary.provider=" + opts.LLMProvider,
		"--set", "global.llmProfiles.primary.model=" + opts.LLMModel,
		"--set", "global.llmProfiles.primary.credentialsSecretName=" + fleetDemoLLMSecretName,
		"--set", fmt.Sprintf("gateway.enabled=%t", opts.Autonomous),
		// Console: always on (BR-PLATFORM-014, Console-first default). Reuses
		// the Traefik ingress + "kubernaut-console" Keycloak client that
		// SetupFleetCoreInfrastructureWithGateway already provisions.
		"--set", "console.enabled=true",
		"--set", "console.auth.secretName=" + fleetDemoConsoleOAuthSecretName,
		// console.ingress.enabled defaults to false (opt-in, same as
		// gateway.ingress.enabled/apifrontend.ingress.enabled --
		// charts/kubernaut/templates/console/ingress.yaml) -- without this,
		// every other console.ingress.* --set below was silently a no-op:
		// no Ingress resource ever rendered, so kubernaut-console.local
		// never resolved to anything through Traefik (issue #2351).
		"--set", "console.ingress.enabled=true",
		"--set", "console.ingress.className=traefik",
		"--set", "console.ingress.host=" + fleetDemoConsoleHost,
		"--set", fmt.Sprintf("console.ingress.port=%d", fleetDemoConsolePort),
		"--set", "networkPolicies.console.ingressNamespaces[0]=" + fleetDemoTraefikNamespace,
		// AF/Console browser+in-cluster OIDC: reuses the same Keycloak fleet
		// infra already stands up (no DEX test double, unlike the FP suite).
		// audience MUST match the kubernaut-apifrontend-audience client scope's
		// oidc-audience-mapper (test/infrastructure/keycloak-realm-fleet.json),
		// else AF's JWTValidator.validateAudience rejects every console token
		// with ErrInvalidAudience -> 401 -> console "Unable to Verify Access"
		// (issue #2352). Mirrors fullpipeline_e2e_helm.go:1088.
		"--set", "apifrontend.config.auth.issuerURL=" + keycloakAuthBase,
		"--set", "apifrontend.config.auth.jwksURL=" + keycloakInClusterBase + "/protocol/openid-connect/certs",
		"--set", "apifrontend.config.auth.audience=kubernaut-apifrontend",
		// Split browser/in-cluster OIDC endpoints (Keycloak lives in its own
		// "idp" namespace, not kubernaut-system -- see keycloak_e2e.go).
		"--set", "console.oauth2Proxy.skipDiscovery=true",
		"--set", "console.oauth2Proxy.loginURL=" + keycloakAuthBase + "/protocol/openid-connect/auth",
		"--set", "console.oauth2Proxy.redeemURL=" + keycloakInClusterBase + "/protocol/openid-connect/token",
		"--set", "console.oauth2Proxy.jwksURL=" + keycloakInClusterBase + "/protocol/openid-connect/certs",
		// Keycloak listens on 8443, not the schema's 443 default -- every
		// fleet-aware service's idpEgress NetworkPolicy rule needs this to
		// reach Keycloak for its own OAuth2 token fetch, and AF additionally
		// uses it for browser-JWT JWKS validation (same host:port, unlike
		// the FP suite's separate DEX-on-5556 case).
		"--set", "networkPolicies.idp.port=8443",
		// AF alert tools (list_alerts/get_alert_details/kubernaut_investigate_alert)
		// only register when the chart renders severityTriage.enabled=true with
		// a prometheusURL, which requires monitoring.prometheus.enabled=true.
		// Without these, AF runs triage-disabled and Console reports alert
		// querying as unconfigured -- even though the fleet monitoring stack
		// below is already running. Matches the manual values printed by
		// SetupFleetCoreInfrastructureWithGateway. Thanos Querier (not plain
		// Prometheus) so alerts are fleet-wide (hub+spoke, ADR-068).
		"--set", "monitoring.prometheus.enabled=true",
		"--set", "monitoring.prometheus.url=http://thanos-querier-svc." + monitoringNamespace + ".svc.cluster.local:9090",
		"--set", "monitoring.alertManager.enabled=true",
		"--set", "monitoring.alertManager.url=http://alertmanager-svc." + monitoringNamespace + ".svc.cluster.local:9093",
		"--set-file", "signalprocessing.policies.content=" + spPolicyFile,
		"--set-file", "aianalysis.policies.content=" + aaPolicyFile,
	}

	if opts.LLMEndpoint != "" {
		// Omitted when empty so vertex_ai installs carry no endpoint at all:
		// every Vertex consumer derives it from project/location (or honors
		// the SDK default), and an explicit empty --set would only obscure
		// that (issue #2355). Same omit-when-empty pattern as ImageTag below.
		args = append(args, "--set", "global.llmProfiles.primary.endpoint="+opts.LLMEndpoint)
	}

	if opts.ImageTag != "" {
		// Optional tag override (global.image.tag, consumed by the chart's
		// kubernaut.image helper). Deliberately omitted when empty so the
		// helper falls back to .Chart.AppVersion -- an unconditional
		// "--set global.image.tag=" here would be shadowed by
		// buildFleetOAuth2HelmArgs below anyway (helm --set is last-wins),
		// which is why a provided override previously never took effect.
		args = append(args, "--set", "global.image.tag="+opts.ImageTag)
	}

	if opts.VertexProject != "" {
		args = append(args, "--set", "global.llmProfiles.primary.vertexProject="+opts.VertexProject)
	}
	if opts.VertexLocation != "" {
		args = append(args, "--set", "global.llmProfiles.primary.vertexLocation="+opts.VertexLocation)
	}

	if opts.Autonomous {
		// AlertManager (Go-managed monitoring stack, deployed by
		// SetupFleetCoreInfrastructureWithGateway into "monitoring") sends
		// webhook signals to Gateway cross-namespace -- same concern
		// InstallFullPipelineHelmChart documents for its own event-exporter.
		args = append(args, "--set", "networkPolicies.gateway.ingressNamespaces[0]="+monitoringNamespace)
	}

	// buildFleetOAuth2HelmArgs (fullpipeline_e2e_helm.go) is the SAME
	// function InstallFullPipelineHelmChart calls for fleet E2E -- a
	// regression here fails fleet E2E CI, not just this demo-only path.
	args = append(args, buildFleetOAuth2HelmArgs(fleetOpts)...)

	return args
}

// buildFleetDemoHelmSecretsManifest renders the Secrets this tool can safely
// generate on the user's behalf -- PostgreSQL/Valkey (random passwords, same
// shape as charts/kubernaut/README.md's own Quick Start) and console-oauth-
// creds for the web Console. Deliberately excludes the LLM credentials
// Secret (fleetDemoLLMSecretName): unlike a random internal password, that
// one requires real, user-specific credentials this tool never reads or
// handles -- the user creates it themselves (README "Try It Out" step 1).
//
// Pure string-building -- callers own generating pgPassword/valkeyPassword/
// consoleCookieSecret, keeping this unit-testable without crypto/rand or
// file I/O.
func buildFleetDemoHelmSecretsManifest(namespace, pgPassword, valkeyPassword, consoleCookieSecret string) string {
	return fmt.Sprintf(`---
apiVersion: v1
kind: Secret
metadata:
  name: %[1]s
  namespace: %[2]s
type: Opaque
stringData:
  POSTGRES_USER: slm_user
  POSTGRES_PASSWORD: %[3]s
  POSTGRES_DB: action_history
  db-secrets.yaml: |
    username: slm_user
    password: %[3]s
---
apiVersion: v1
kind: Secret
metadata:
  name: %[4]s
  namespace: %[2]s
type: Opaque
stringData:
  valkey-secrets.yaml: |
    password: %[5]s
---
apiVersion: v1
kind: Secret
metadata:
  name: %[6]s
  namespace: %[2]s
type: Opaque
stringData:
  client-id: %[7]s
  client-secret: %[8]s
  cookie-secret: %[9]s
`,
		fleetDemoPGSecretName, namespace, pgPassword,
		fleetDemoValkeySecretName, valkeyPassword,
		fleetDemoConsoleOAuthSecretName, fleetDemoConsoleClientID, fleetDemoConsoleClientSecret, consoleCookieSecret)
}

// generateFleetDemoSecret returns a random, URL-safe base64 string of n
// random bytes -- the Go-native equivalent of `openssl rand -base64 n` used
// by charts/kubernaut/README.md's own Quick Start.
func generateFleetDemoSecret(n int) (string, error) {
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("failed to generate random secret: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// checkSecretExists returns nil if a Secret named secretName exists in
// namespace, or the underlying `kubectl get` error otherwise. Used to fail
// fast with an actionable, kubectl-command-shaped error instead of letting
// the user discover a missing Secret only after `helm install` runs (and
// the chart's own pre-install validation rejects it less specifically).
func checkSecretExists(ctx context.Context, kubeconfigPath, namespace, secretName string) error {
	cmd := exec.CommandContext(ctx, "kubectl", "--kubeconfig", kubeconfigPath,
		"-n", namespace, "get", "secret", secretName)
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	return cmd.Run()
}

// InstallFleetDemoHelmChart is the exported, post-fleet-core-infra entry
// point for hack/setup-fleet-infra (Issue #2337): verifies the user-created
// LLM Secret exists, creates the remaining prerequisite Secrets, writes the
// Rego policy files, runs `helm upgrade --install charts/kubernaut`, and
// binds the AF persona RBAC Console needs immediately (previously separate
// manual steps -- README Quick Start's secrets, `--set-file` policies, and
// `make bind-fleet-af-rbac`).
//
// fleetOpts comes from SetupFleetCoreInfrastructureWithGateway's return
// value -- must be non-nil for fleet federation to actually work, but the
// nil case is still handled (mirrors InstallFullPipelineHelmChart) so a
// caller without fleet infra can still install a non-fleet chart.
func InstallFleetDemoHelmChart(ctx context.Context, kubeconfigPath, remoteKubeconfigPath string, fleetOpts *FleetHelmOptions, opts FleetDemoHelmOptions, writer io.Writer) error {
	if err := opts.Validate(); err != nil {
		return err
	}

	namespace := kubernautSystem
	projectRoot := getProjectRoot()
	chartPath := filepath.Join(projectRoot, "charts", "kubernaut")

	namespaceManifest := fmt.Sprintf("apiVersion: v1\nkind: Namespace\nmetadata:\n  name: %s\n", namespace)
	if err := kubectlApplyManifest(ctx, kubeconfigPath, writer, namespaceManifest); err != nil {
		return fmt.Errorf("failed to create %s namespace: %w", namespace, err)
	}

	_, _ = fmt.Fprintf(writer, "\n🔑 Checking for %s Secret (must be created by you first)...\n", fleetDemoLLMSecretName)
	if err := checkSecretExists(ctx, kubeconfigPath, namespace, fleetDemoLLMSecretName); err != nil {
		return fmt.Errorf(
			"%s Secret not found in namespace %q -- create it before running this command:\n"+
				"  kubectl create secret generic %s --from-literal=api_key=<your-llm-api-key> -n %s\n(%w)",
			fleetDemoLLMSecretName, namespace, fleetDemoLLMSecretName, namespace, err)
	}
	_, _ = fmt.Fprintln(writer, "  ✅ Found")

	_, _ = fmt.Fprintln(writer, "\n🔑 Creating remaining prerequisite Secrets (postgresql, valkey, console-oauth)...")
	pgPassword, err := generateFleetDemoSecret(24)
	if err != nil {
		return err
	}
	valkeyPassword, err := generateFleetDemoSecret(24)
	if err != nil {
		return err
	}
	consoleCookieSecret, err := generateFleetDemoSecret(32)
	if err != nil {
		return err
	}

	secretsManifest := buildFleetDemoHelmSecretsManifest(namespace, pgPassword, valkeyPassword, consoleCookieSecret)
	if err := kubectlApplyManifest(ctx, kubeconfigPath, writer, secretsManifest); err != nil {
		return fmt.Errorf("failed to create prerequisite Secrets: %w", err)
	}
	_, _ = fmt.Fprintln(writer, "  ✅ Secrets ready")

	tmpDir, err := os.MkdirTemp("", "fleet-demo-policies-*")
	if err != nil {
		return fmt.Errorf("failed to create temp dir for policy files: %w", err)
	}
	defer func() {
		if rmErr := os.RemoveAll(tmpDir); rmErr != nil {
			_, _ = fmt.Fprintf(writer, "⚠️  Failed to clean up temp policy dir %s: %v\n", tmpDir, rmErr)
		}
	}()

	spPolicyFile := opts.SPPolicyFile
	if spPolicyFile == "" {
		spPolicyFile = filepath.Join(tmpDir, "sp-policy.rego")
		if writeErr := os.WriteFile(spPolicyFile, []byte(fleetDemoDefaultSPPolicyRego), 0o644); writeErr != nil {
			return fmt.Errorf("failed to write default SignalProcessing policy: %w", writeErr)
		}
	}
	aaPolicyFile := opts.AAPolicyFile
	if aaPolicyFile == "" {
		aaPolicyFile = filepath.Join(tmpDir, "aa-policy.rego")
		if writeErr := os.WriteFile(aaPolicyFile, []byte(fleetDemoDefaultAAPolicyRego), 0o644); writeErr != nil {
			return fmt.Errorf("failed to write default AIAnalysis policy: %w", writeErr)
		}
	}

	args := buildFleetDemoHelmArgs(kubeconfigPath, chartPath, namespace, fleetOpts, opts, spPolicyFile, aaPolicyFile)

	_, _ = fmt.Fprintf(writer, "\n🚀 helm upgrade --install kubernaut charts/kubernaut %s", args)
	cmd := exec.CommandContext(ctx, "helm", args...)
	cmd.Stdout = writer
	cmd.Stderr = writer
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("helm install failed: %w", err)
	}
	_, _ = fmt.Fprintln(writer, "  ✅ Helm chart installed")

	_, _ = fmt.Fprintln(writer, "\n🔑 Binding AF persona RBAC for Console...")
	if err := BindFleetAFPersonaRBAC(ctx, kubeconfigPath, writer); err != nil {
		return fmt.Errorf("failed to bind AF persona RBAC: %w", err)
	}

	_, _ = fmt.Fprintln(writer, "\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	_, _ = fmt.Fprintln(writer, "✅ Kubernaut installed and ready")
	_, _ = fmt.Fprintln(writer, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
	_, _ = fmt.Fprintln(writer, "  Add this line to /etc/hosts yourself (never edited automatically):")
	_, _ = fmt.Fprintf(writer, "    127.0.0.1 keycloak %s\n", fleetDemoConsoleHost)
	_, _ = fmt.Fprintf(writer, "  Browse to:          https://%s:%d\n", fleetDemoConsoleHost, fleetDemoConsolePort)
	_, _ = fmt.Fprintln(writer, "  Login:              sre-user / password")
	if opts.Autonomous {
		_, _ = fmt.Fprintln(writer, "  Gateway is ENABLED -- demo scenario alerts remediate autonomously.")
	} else {
		_, _ = fmt.Fprintln(writer, "  Gateway is disabled -- run a demo scenario with --alert-only, then ask")
		_, _ = fmt.Fprintln(writer, "  Console to investigate. Re-run with -autonomous to see it happen on its own.")
	}
	_, _ = fmt.Fprintln(writer, "\n  To run a kubernaut-demo-scenarios scenario in fleet mode (hub+spoke split")
	_, _ = fmt.Fprintln(writer, "  instead of single-cluster), export these, then run the scenario:")
	_, _ = fmt.Fprintf(writer, "    export HUB_KUBECONFIG=%s\n", kubeconfigPath)
	_, _ = fmt.Fprintf(writer, "    export SPOKE_KUBECONFIG=%s\n", remoteKubeconfigPath)
	_, _ = fmt.Fprintln(writer, "\n  Clone the demo scenarios repo:")
	_, _ = fmt.Fprintln(writer, "    git clone https://github.com/kubernaut/kubernaut-demo-scenarios.git")
	_, _ = fmt.Fprintln(writer, "    cd kubernaut-demo-scenarios https://github.com/kubernaut/kubernaut-demo-scenarios.git")
	if opts.Autonomous {
		_, _ = fmt.Fprintln(writer, "    ./scenarios/<name>/run.sh --fleet")
		_, _ = fmt.Fprintln(writer, "  (Gateway enabled: Kubernaut detects and remediates automatically.)")
	} else {
		_, _ = fmt.Fprintln(writer, "    ./scenarios/<name>/run.sh --fleet --alert-only")
		_, _ = fmt.Fprintln(writer, "  (--alert-only fires the alert and stops: investigate it yourself in")
		_, _ = fmt.Fprintln(writer, "  Console. Drop --alert-only with -autonomous for full auto-remediation.)")
	}
	_, _ = fmt.Fprintln(writer, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

	return nil
}
