apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus-alerts-slm
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/secret.yaml
  - manifests/rbac.yaml
  - manifests/localai-deployment.yaml
  - manifests/app-deployment.yaml
  - manifests/monitoring.yaml
  - manifests/route.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: "kustomize"

# Namespace for all resources
namespace: prometheus-alerts-slm

# Image configurations
images:
  - name: quay.io/jordigilh/prometheus-alerts-slm
    newTag: latest
  - name: quay.io/go-skynet/local-ai
    newTag: latest

# Resource patches for different environments
patchesStrategicMerge:
  - patches/resource-limits.yaml

# ConfigMap generator for environment-specific configs
configMapGenerator:
  - name: deployment-config
    literals:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - DRY_RUN=false

# Secret generator (use with external secret management)
secretGenerator:
  - name: webhook-secrets
    literals:
      - webhook-token=changeme