apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: kubernaut-integration
  labels:
    app: prometheus
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: prometheus
  selector:
    app: prometheus
---
# NodePort service for external access during development
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: kubernaut-integration
  labels:
    app: prometheus
    component: monitoring
    service-type: external-access
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
    protocol: TCP
    name: prometheus
  selector:
    app: prometheus
