apiVersion: v2
name: kubernaut
description: Kubernaut - Autonomous Kubernetes Remediation Platform
type: application
version: 1.1.0-rc0
appVersion: "v1.1.0-rc0"
home: https://github.com/jordigilh/kubernaut
sources:
  - https://github.com/jordigilh/kubernaut
maintainers:
  - name: Jordi Gil
    url: https://github.com/jordigilh
keywords:
  - kubernetes
  - remediation
  - ai
  - observability
  - automation
