apiVersion: apps/v1
kind: Deployment
metadata:
  name: holmesgpt
  namespace: kubernaut-integration
  labels:
    app: holmesgpt
    component: kubernaut
    service: holmesgpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: holmesgpt
  template:
    metadata:
      labels:
        app: holmesgpt
        component: kubernaut
        service: holmesgpt
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: kubernaut-holmesgpt
      containers:
      - name: holmesgpt
        image: kubernaut/holmesgpt-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
          name: http
        - containerPort: 9091
          name: metrics
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: POSTGRES_HOST
          value: "postgresql-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgresql-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: LLM_ENDPOINT
          value: "http://192.168.1.169:8080"  # External LLM endpoint
        - name: LLM_PROVIDER
          value: "ollama"
        - name: LLM_MODEL
          value: "hf://ggml-org/gpt-oss-20b-GGUF"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: holmesgpt-service
  namespace: kubernaut-integration
  labels:
    app: holmesgpt
    component: kubernaut
    service: holmesgpt
spec:
  type: ClusterIP
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: holmesgpt
