apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernaut-webhook
  namespace: kubernaut-integration
  labels:
    app: kubernaut
    component: webhook
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernaut-ai
  namespace: kubernaut-integration
  labels:
    app: kubernaut
    component: ai
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernaut-holmesgpt
  namespace: kubernaut-integration
  labels:
    app: kubernaut
    component: holmesgpt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernaut-webhook
  labels:
    app: kubernaut
    component: webhook
rules:
# Kubernetes API access for webhook operations
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - nodes
  - namespaces
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs: ["get", "list"]
# Events for monitoring and alerting
- apiGroups: [""]
  resources:
  - events
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernaut-ai
  labels:
    app: kubernaut
    component: ai
rules:
# Read-only access for AI analysis
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - nodes
  - namespaces
  - events
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs: ["get", "list"]
# Limited write access for AI-driven actions
- apiGroups: [""]
  resources:
  - pods
  verbs: ["delete"]  # For pod restart actions
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  verbs: ["patch"]  # For scaling actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernaut-webhook
  labels:
    app: kubernaut
    component: webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernaut-webhook
subjects:
- kind: ServiceAccount
  name: kubernaut-webhook
  namespace: kubernaut-integration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernaut-ai
  labels:
    app: kubernaut
    component: ai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernaut-ai
subjects:
- kind: ServiceAccount
  name: kubernaut-ai
  namespace: kubernaut-integration
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernaut-holmesgpt
  labels:
    app: kubernaut
    component: holmesgpt
rules:
# Read-only access for HolmesGPT analysis
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - nodes
  - namespaces
  - events
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - pods
  - nodes
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernaut-holmesgpt
  labels:
    app: kubernaut
    component: holmesgpt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernaut-holmesgpt
subjects:
- kind: ServiceAccount
  name: kubernaut-holmesgpt
  namespace: kubernaut-integration
