---
apiVersion: v1
kind: ConfigMap
metadata:
  name: holmesgpt-api-config
  namespace: kubernaut-ai
  labels:
    app.kubernetes.io/name: holmesgpt-api
    app.kubernetes.io/component: ai-analysis
    app.kubernetes.io/part-of: kubernaut
data:
  # Application configuration
  LOG_LEVEL: "info"
  DEV_MODE: "false"

  # API configuration
  API_HOST: "0.0.0.0"
  API_PORT: "8080"

  # Kubernetes service discovery
  KUBERNETES_SERVICE_HOST: "kubernetes.default.svc"
  KUBERNETES_SERVICE_PORT: "443"



