---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: holmesgpt-api
  namespace: kubernaut-system
  labels:
    app.kubernetes.io/name: holmesgpt-api
    app.kubernetes.io/part-of: kubernaut
    app.kubernetes.io/component: api-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: holmesgpt-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
  namespaceSelector:
    matchNames:
      - kubernaut-system


