// Code generated by ogen, DO NOT EDIT.
package api

type CreateAuditEventRes interface {
	createAuditEventRes()
}

type CreateNotificationAuditRes interface {
	createNotificationAuditRes()
}

type CreateWorkflowRes interface {
	createWorkflowRes()
}

type DisableWorkflowRes interface {
	disableWorkflowRes()
}

type ExportAuditEventsRes interface {
	exportAuditEventsRes()
}

type GetWorkflowByIDRes interface {
	getWorkflowByIDRes()
}

type HealthCheckRes interface {
	healthCheckRes()
}

type ListWorkflowsRes interface {
	listWorkflowsRes()
}

type PlaceLegalHoldRes interface {
	placeLegalHoldRes()
}

type ReadinessCheckRes interface {
	readinessCheckRes()
}

type ReleaseLegalHoldRes interface {
	releaseLegalHoldRes()
}

type SearchWorkflowsRes interface {
	searchWorkflowsRes()
}

type UpdateWorkflowRes interface {
	updateWorkflowRes()
}
