# Kubernaut Integration Environment Shortcuts
# Generated by setup-core-integration-environment.sh
# Include this in your main Makefile: include scripts/integration-env-shortcuts.mk

.PHONY: setup-integration-env clean-integration-env validate-integration-env run-integration-tests

# Setup complete integration environment
setup-integration-env:
	@echo "🚀 Setting up core services integration environment..."
	@./scripts/setup-core-integration-environment.sh

# Clean integration environment
clean-integration-env:
	@echo "🧹 Cleaning integration environment..."
	@./scripts/setup-core-integration-environment.sh --clean

# Setup for Cursor IDE
setup-integration-env-cursor:
	@echo "🎯 Setting up integration environment for Cursor IDE..."
	@./scripts/setup-core-integration-environment.sh --cursor

# Validate integration environment
validate-integration-env:
	@echo "✅ Validating integration environment..."
	@./scripts/setup-core-integration-environment.sh --dry-run

# Run core integration tests
run-integration-tests:
	@echo "🧪 Running core services integration tests..."
	@source .env.integration 2>/dev/null || true && \
	go test -v -tags=integration ./test/integration/core_integration/ -timeout=30m

# Run specific integration test suites
run-integration-tests-ai:
	@source .env.integration 2>/dev/null || true && \
	go test -v -tags=integration ./test/integration/ai/ -timeout=20m

run-integration-tests-external:
	@source .env.integration 2>/dev/null || true && \
	go test -v -tags=integration ./test/integration/external_services/ -timeout=15m

# Quick integration test (skip slow tests)
run-integration-tests-quick:
	@source .env.integration 2>/dev/null || true && \
	SKIP_SLOW_TESTS=true go test -v -tags=integration ./test/integration/core_integration/ -timeout=10m

# Load integration environment variables
load-integration-env:
	@echo "🔧 To load integration environment, run:"
	@echo "   source ./scripts/activate-integration-env.sh"

# Show integration environment status
show-integration-status:
	@echo "📋 Integration Environment Status:"
	@echo "Kind Clusters:"
	@kind get clusters | grep kubernaut || echo "  No kubernaut clusters found"
	@echo ""
	@echo "Docker Services:"
	@docker ps --format "table {{.Names}}\t{{.Status}}" | grep kubernaut || echo "  No kubernaut containers running"
	@echo ""
	@echo "Environment File:"
	@ls -la .env.integration 2>/dev/null || echo "  .env.integration not found"
