//go:build !ignore_autogenerated

/*
Copyright 2025 Jordi Gil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAComponents) DeepCopyInto(out *EAComponents) {
	*out = *in
	if in.HealthScore != nil {
		in, out := &in.HealthScore, &out.HealthScore
		*out = new(float64)
		**out = **in
	}
	if in.AlertScore != nil {
		in, out := &in.AlertScore, &out.AlertScore
		*out = new(float64)
		**out = **in
	}
	if in.MetricsScore != nil {
		in, out := &in.MetricsScore, &out.MetricsScore
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAComponents.
func (in *EAComponents) DeepCopy() *EAComponents {
	if in == nil {
		return nil
	}
	out := new(EAComponents)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EAConfig) DeepCopyInto(out *EAConfig) {
	*out = *in
	out.StabilizationWindow = in.StabilizationWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EAConfig.
func (in *EAConfig) DeepCopy() *EAConfig {
	if in == nil {
		return nil
	}
	out := new(EAConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivenessAssessment) DeepCopyInto(out *EffectivenessAssessment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivenessAssessment.
func (in *EffectivenessAssessment) DeepCopy() *EffectivenessAssessment {
	if in == nil {
		return nil
	}
	out := new(EffectivenessAssessment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EffectivenessAssessment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivenessAssessmentList) DeepCopyInto(out *EffectivenessAssessmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EffectivenessAssessment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivenessAssessmentList.
func (in *EffectivenessAssessmentList) DeepCopy() *EffectivenessAssessmentList {
	if in == nil {
		return nil
	}
	out := new(EffectivenessAssessmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EffectivenessAssessmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivenessAssessmentSpec) DeepCopyInto(out *EffectivenessAssessmentSpec) {
	*out = *in
	out.TargetResource = in.TargetResource
	out.Config = in.Config
	if in.RemediationCreatedAt != nil {
		in, out := &in.RemediationCreatedAt, &out.RemediationCreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivenessAssessmentSpec.
func (in *EffectivenessAssessmentSpec) DeepCopy() *EffectivenessAssessmentSpec {
	if in == nil {
		return nil
	}
	out := new(EffectivenessAssessmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EffectivenessAssessmentStatus) DeepCopyInto(out *EffectivenessAssessmentStatus) {
	*out = *in
	if in.ValidityDeadline != nil {
		in, out := &in.ValidityDeadline, &out.ValidityDeadline
		*out = (*in).DeepCopy()
	}
	if in.PrometheusCheckAfter != nil {
		in, out := &in.PrometheusCheckAfter, &out.PrometheusCheckAfter
		*out = (*in).DeepCopy()
	}
	if in.AlertManagerCheckAfter != nil {
		in, out := &in.AlertManagerCheckAfter, &out.AlertManagerCheckAfter
		*out = (*in).DeepCopy()
	}
	in.Components.DeepCopyInto(&out.Components)
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EffectivenessAssessmentStatus.
func (in *EffectivenessAssessmentStatus) DeepCopy() *EffectivenessAssessmentStatus {
	if in == nil {
		return nil
	}
	out := new(EffectivenessAssessmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetResource) DeepCopyInto(out *TargetResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetResource.
func (in *TargetResource) DeepCopy() *TargetResource {
	if in == nil {
		return nil
	}
	out := new(TargetResource)
	in.DeepCopyInto(out)
	return out
}
