# Redis StatefulSet with Sentinel for Gateway Service High Availability
# BR-GATEWAY-008, BR-GATEWAY-009: Ensures deduplication/storm detection always available
---
apiVersion: v1
kind: Service
metadata:
  name: redis-gateway-headless
  namespace: kubernaut-system
  labels:
    app: redis-gateway
    component: redis
    service: gateway
spec:
  clusterIP: None
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: sentinel
    port: 26379
    targetPort: 26379
  selector:
    app: redis-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: redis-gateway-ha
  namespace: kubernaut-system
  labels:
    app: redis-gateway
    component: redis
    service: gateway
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: sentinel
    port: 26379
    targetPort: 26379
  selector:
    app: redis-gateway

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-gateway
  namespace: kubernaut-system
  labels:
    app: redis-gateway
    component: redis
    service: gateway
spec:
  serviceName: redis-gateway-headless
  replicas: 3  # 3 Redis instances for HA
  selector:
    matchLabels:
      app: redis-gateway
  template:
    metadata:
      labels:
        app: redis-gateway
        component: redis
        service: gateway
    spec:
      initContainers:
      - name: init-redis
        image: redis:7-alpine
        command:
        - sh
        - -c
        - |
          set -ex
          # Copy default config
          cp /mnt/config-map/redis.conf /etc/redis/redis.conf

          # Determine if this is master or replica
          if [ "$(hostname)" = "redis-gateway-0" ]; then
            echo "This is redis-gateway-0 (master)"
          else
            echo "This is a replica, configuring replication"
            echo "replicaof redis-gateway-0.redis-gateway-headless.kubernaut-system.svc.cluster.local 6379" >> /etc/redis/redis.conf
          fi
        volumeMounts:
        - name: redis-config
          mountPath: /mnt/config-map
        - name: config
          mountPath: /etc/redis

      containers:
      - name: redis
        image: redis:7-alpine
        command:
        - redis-server
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: config
          mountPath: /etc/redis
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5

      - name: sentinel
        image: redis:7-alpine
        command:
        - sh
        - -c
        - |
          # Copy sentinel config to writable location
          cp /etc/redis-sentinel-ro/sentinel.conf /tmp/sentinel.conf
          # Start sentinel with writable config
          redis-sentinel /tmp/sentinel.conf
        ports:
        - containerPort: 26379
          name: sentinel
        volumeMounts:
        - name: sentinel-config
          mountPath: /etc/redis-sentinel-ro
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 26379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "26379"
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: redis-config
        configMap:
          name: redis-gateway-config
      - name: sentinel-config
        configMap:
          name: redis-gateway-sentinel-config
      - name: config
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-gateway-config
  namespace: kubernaut-system
  labels:
    app: redis-gateway
    component: redis
    service: gateway
data:
  redis.conf: |
    # Redis configuration for Gateway Service
    bind 0.0.0.0
    protected-mode no
    port 6379

    # Persistence
    save 900 1
    save 300 10
    save 60 10000

    # Memory
    maxmemory 256mb
    maxmemory-policy allkeys-lru

    # Replication
    replica-read-only yes

    # Logging
    loglevel notice

