# Redis Sentinel ConfigMap for Gateway Service High Availability
# BR-GATEWAY-008, BR-GATEWAY-009: Redis HA ensures deduplication/storm detection availability
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-gateway-sentinel-config
  namespace: kubernaut-system
  labels:
    app: redis-gateway
    component: sentinel
    service: gateway
data:
  sentinel.conf: |
    # Sentinel configuration for Gateway Redis HA
    port 26379
    dir /tmp

    # Monitor Redis master
    # sentinel monitor <master-name> <ip> <port> <quorum>
    # quorum=2: need 2 sentinels to agree on master failure
    # Use service name (Sentinel will resolve to actual master IP)
    sentinel monitor gateway-master redis-gateway-ha.kubernaut-system.svc.cluster.local 6379 2

    # Timeouts and thresholds
    sentinel down-after-milliseconds gateway-master 5000
    sentinel parallel-syncs gateway-master 1
    sentinel failover-timeout gateway-master 10000
    
    # Sentinel will automatically discover master IP and update config
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes

    # Authentication (if Redis has password)
    # sentinel auth-pass gateway-master <password>

