# Redis Sentinel ConfigMap for High Availability
# BR-GATEWAY-008, BR-GATEWAY-009: Redis HA ensures deduplication/storm detection availability
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: kubernaut-system
data:
  sentinel.conf: |
    # Sentinel configuration for Redis HA
    port 26379
    dir /tmp

    # Monitor Redis master
    # sentinel monitor <master-name> <ip> <port> <quorum>
    # quorum=2: need 2 sentinels to agree on master failure
    sentinel monitor mymaster redis-0.redis-headless.kubernaut-system.svc.cluster.local 6379 2

    # Timeouts and thresholds
    sentinel down-after-milliseconds mymaster 5000
    sentinel parallel-syncs mymaster 1
    sentinel failover-timeout mymaster 10000

    # Authentication (if Redis has password)
    # sentinel auth-pass mymaster <password>


