//go:build !ignore_autogenerated

/*
Copyright 2025 Jordi Gil.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflow) DeepCopyInto(out *RemediationWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflow.
func (in *RemediationWorkflow) DeepCopy() *RemediationWorkflow {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowDependencies) DeepCopyInto(out *RemediationWorkflowDependencies) {
	*out = *in
	if in.Secrets != nil {
		in, out := &in.Secrets, &out.Secrets
		*out = make([]RemediationWorkflowResourceDependency, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMaps != nil {
		in, out := &in.ConfigMaps, &out.ConfigMaps
		*out = make([]RemediationWorkflowResourceDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowDependencies.
func (in *RemediationWorkflowDependencies) DeepCopy() *RemediationWorkflowDependencies {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowDependencies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowDescription) DeepCopyInto(out *RemediationWorkflowDescription) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowDescription.
func (in *RemediationWorkflowDescription) DeepCopy() *RemediationWorkflowDescription {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowDescription)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowExecution) DeepCopyInto(out *RemediationWorkflowExecution) {
	*out = *in
	if in.EngineConfig != nil {
		in, out := &in.EngineConfig, &out.EngineConfig
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowExecution.
func (in *RemediationWorkflowExecution) DeepCopy() *RemediationWorkflowExecution {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowExecution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowLabels) DeepCopyInto(out *RemediationWorkflowLabels) {
	*out = *in
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Environment != nil {
		in, out := &in.Environment, &out.Environment
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowLabels.
func (in *RemediationWorkflowLabels) DeepCopy() *RemediationWorkflowLabels {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowLabels)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowList) DeepCopyInto(out *RemediationWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowList.
func (in *RemediationWorkflowList) DeepCopy() *RemediationWorkflowList {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemediationWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowMaintainer) DeepCopyInto(out *RemediationWorkflowMaintainer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowMaintainer.
func (in *RemediationWorkflowMaintainer) DeepCopy() *RemediationWorkflowMaintainer {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowMaintainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowMetadata) DeepCopyInto(out *RemediationWorkflowMetadata) {
	*out = *in
	out.Description = in.Description
	if in.Maintainers != nil {
		in, out := &in.Maintainers, &out.Maintainers
		*out = make([]RemediationWorkflowMaintainer, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowMetadata.
func (in *RemediationWorkflowMetadata) DeepCopy() *RemediationWorkflowMetadata {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowParameter) DeepCopyInto(out *RemediationWorkflowParameter) {
	*out = *in
	if in.Enum != nil {
		in, out := &in.Enum, &out.Enum
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowParameter.
func (in *RemediationWorkflowParameter) DeepCopy() *RemediationWorkflowParameter {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowParameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowResourceDependency) DeepCopyInto(out *RemediationWorkflowResourceDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowResourceDependency.
func (in *RemediationWorkflowResourceDependency) DeepCopy() *RemediationWorkflowResourceDependency {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowResourceDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowSpec) DeepCopyInto(out *RemediationWorkflowSpec) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Labels.DeepCopyInto(&out.Labels)
	if in.CustomLabels != nil {
		in, out := &in.CustomLabels, &out.CustomLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DetectedLabels != nil {
		in, out := &in.DetectedLabels, &out.DetectedLabels
		*out = new(v1.JSON)
		(*in).DeepCopyInto(*out)
	}
	in.Execution.DeepCopyInto(&out.Execution)
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = new(RemediationWorkflowDependencies)
		(*in).DeepCopyInto(*out)
	}
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]RemediationWorkflowParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RollbackParameters != nil {
		in, out := &in.RollbackParameters, &out.RollbackParameters
		*out = make([]RemediationWorkflowParameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowSpec.
func (in *RemediationWorkflowSpec) DeepCopy() *RemediationWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationWorkflowStatus) DeepCopyInto(out *RemediationWorkflowStatus) {
	*out = *in
	if in.RegisteredAt != nil {
		in, out := &in.RegisteredAt, &out.RegisteredAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationWorkflowStatus.
func (in *RemediationWorkflowStatus) DeepCopy() *RemediationWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}
