---
# Kubernaut Must-Gather - ClusterRole
# BR-PLATFORM-001.3.2: RBAC requirements for diagnostic collection
# Grants read-only access to all Kubernaut resources and infrastructure

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernaut-must-gather
  labels:
    app.kubernetes.io/name: must-gather
    app.kubernetes.io/part-of: kubernaut
    app.kubernetes.io/component: diagnostics
rules:
# Core Kubernetes resources
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - events
    - configmaps
    - secrets
    - nodes
    - namespaces
    - services
    - endpoints
    - persistentvolumeclaims
    - persistentvolumes
    - serviceaccounts
  verbs: ["get", "list"]

# Apps resources
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - statefulsets
    - daemonsets
  verbs: ["get", "list"]

# Kubernaut CRDs (all 6 types)
- apiGroups: ["kubernaut.ai"]
  resources:
    - remediationrequests
    - remediationapprovalrequests
    - signalprocessings
    - aianalyses
    - workflowexecutions
    - notificationrequests
  verbs: ["get", "list"]

# Tekton resources (CRITICAL for V1.0)
- apiGroups: ["tekton.dev"]
  resources:
    - pipelineruns
    - taskruns
    - pipelines
    - tasks
    - pipelineresources
  verbs: ["get", "list"]

# CRD definitions
- apiGroups: ["apiextensions.k8s.io"]
  resources:
    - customresourcedefinitions
  verbs: ["get", "list"]

# RBAC resources (for RBAC collection)
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - clusterroles
    - clusterrolebindings
    - roles
    - rolebindings
  verbs: ["get", "list"]

# Storage resources
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - volumeattachments
  verbs: ["get", "list"]

# Networking resources
- apiGroups: ["networking.k8s.io"]
  resources:
    - networkpolicies
    - ingresses
  verbs: ["get", "list"]

# OpenShift Routes (if running on OpenShift)
- apiGroups: ["route.openshift.io"]
  resources:
    - routes
  verbs: ["get", "list"]

# Monitoring resources
- apiGroups: ["monitoring.coreos.com"]
  resources:
    - servicemonitors
    - prometheusrules
  verbs: ["get", "list"]

# Webhook configurations
- apiGroups: ["admissionregistration.k8s.io"]
  resources:
    - validatingwebhookconfigurations
    - mutatingwebhookconfigurations
  verbs: ["get", "list"]

